sonic-net/sonic-platform-common

sonic_sfp/sff8436.py

add Connector type, encoding, identifier, extend identifier sub-item for qsfp28
Before the modification 
sudo sfputil show eeprom -p Ethernet31
Ethernet31: SFP EEPROM detected
Connector: Unknown
Encoding: Unknown
Extended Identifier: Unknown
Extended RateSelect Compliance: QSFP+ Rate Select Version 1
Identifier: Unknown
Length Cable Assembly(m): 50
Length OM3(2m): 35
Nominal Bit Rate(100Mbs): 255
Specification compliance:
Fibre Channel link length/Transmitter Technology: Short distance (S)
Fibre Channel transmission media: Shielded Twisted Pair (TP)
Vendor Date Code(YYYY-MM-DD Lot): 2018-01-26
Vendor Name: WTD
Vendor OUI: 00-1c-ad
Vendor PN: RTXM420-550
Vendor Rev: 21
Vendor SN: WA180400120006
after the modification
sudo sfputil show eeprom -p Ethernet31
Ethernet31: SFP EEPROM detected …

[sonic_sfp] add support for qsfp28 eeprom

---

sonic_sfp/bcmshell.py

New SAI appears to have changed the amount of whitespace in the Broadcom shell.
Previous output: `bcmshell\r\ndrivshell>`
New output: `bcmshell\r\n\r\r\ndrivshell>`
This change caused bcmshell.py to consistently fail.
This PR now matches any additional whitespace between `bcmshell\r\n` and `drivshell>`

[bcmshell.py] Match extra whitespace before prompt in regex

---

sonic_sfp/sfputilbase.py

With adding more columns into the port_config.ini file, the previous
logic of checking len(line.split()) == 4 is no longer valid. With
adding the logic of parsing the title of the file, the port index
could be directly retrieved depending on which column it is.
Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

[sfputilbase]: Add logic to parse the title of port_config.ini file

---

sonic_eeprom/eeprom_base.py
sonic_eeprom/eeprom_tlvinfo.py
sonic_sfp/bcmshell.py
sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sffbase.py
sonic_sfp/sfputilbase.py

We are packaging sonic-platform-common as both a Python 2 wheel and Python 3 wheel. Currently, with Python 3 we only use sonic_psu in the SNMP docker, which is already compliant with both Python 2 and 3.
However, when installing the Python 3 package, I noticed there were multiple error messages because of eeprom and sfp files which were not Python 3-compatible. Since the Python 3 implementation of these files is not currently used, no issues were presented in the image itself.
This PR causes both the Python 2 and Python 3 wheel packages to build and install without any errors.

More changes for compatibility with both Python 2 and 3

---

sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sfputilbase.py

[sfputilbase]: enhance the sfputilbase for transceiver monitoring
[List of changes]
* add ability to only read and parse specific bytes from eeprom
* add two API to read the transceiver info and dom info which intrested by SNMP
* add a new API definiton: get_transceiver_change_event
* fix a bug: wrong 'VendorOUI' offset for sff8472
modified:   sff8436.py
modified:   sff8472.py
modified:   sfputilbase.py
Signed-off-by Liu Kebo kebol@mellanox.com

[sfputilbase]: enhance the sfputilbase for transceiver monitoring

---

sonic_eeprom/eeprom_base.py

Before this PR, if a corrupt cache file exists, decode-syseeprom will fail indefinitely until the file is manually deleted.

[sonic_eeprom] If reading from what appears to be a corrupt cache file, delete file and read directly from EEPROM

---

sonic_sfp/sff8472.py

The VendorOUI should decode as hex.

[sff8472] Fix incorrect VendorOUI decode type.

---

sonic_sfp/sfputilbase.py

Buffering will cause read to read more than requested. For slow files
like SFP EEPROM, we want to read exactly what we asked for.
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[sfp_util] open eeprom files with buffering disabled

---

sonic_eeprom/eeprom_base.py
sonic_eeprom/eeprom_tlvinfo.py

Add two new function update_eeprom_db() and read_eeprom_db() to support
update and print EEPROM information from redis database directly.
Signed-off-by: Kevin Wang <kevinw@mellanox.com>

Write the contents of EEPROM to database

---

sonic_sfp/sfputilbase.py

remove the problematic gang port handling code from the "port_config.ini" parsing function, it can generate a wrong port mapping table in some port break case.

[sonic_sfp] Remove problematic gang port handling code

---

sonic_eeprom/eeprom_base.py
sonic_eeprom/eeprom_dts.py
sonic_eeprom/eeprom_tlvinfo.py
sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sfputilbase.py

Signed-off-by: Sangita Maity [samaity@linkedin.com](mailto:samaity@linkedin.com)
**- What I did**
I was getting lots of import error during SNMP docker upgrade to stretch build. Made changes accordingly to fix those issues. May be python compatibility issue as by default it is using python3 and there's no exceptions module in python3
**- How I did it**
Made it compatible with python3 whenever required.
**- How to verify it**
Use this PR with snmp docker upgrade PR in sonic-buildimage.

changes needed for SNMP docker upgrade to stretch build

---

sonic_platform_base/chassis_base.py
sonic_platform_base/psu_base.py

sonic_platform_base: fix two typos in platform base class API.
```
modified:   chassis_base.py
modified:   psu_base.py
```
Signed-off-by: Liu Kebo kebol@mellanox.com

[sonic_platform_base] Fix typos in platform base class api

---

sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sfputilbase.py

```
sonic_sfp: Extend sfputilbase to support xcvrd get more fields from SFP eeprom.
* Extends sff8446 and sff8472 with more fields parsing functions.
* Extend sfputilbase to return more fields to xcvrd.
* Add handling for OSFP. 
Signed-off-by: Kebo Liu kebol@mellanox.com
```

[sonic_sfp] Extend sfpbase to get more info from SFP eeprom for xcvrd

---

sonic_sfp/inf8628.py
sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sfputilbase.py

Signed-off-by: Sangita Maity samaity@linkedin.com
- **What I did**
I was getting lots of import error during SNMP docker upgrade to stretch build. Made changes accordingly to fix those issues. May be python compatibility issue as by default it is using python3 and there's no exceptions module in python3
- **How I did it**
Made it compatible with python3 whenever required.
- **How to verify it**
Use this PR with snmp docker upgrade PR in sonic-buildimage.

more changes needed for SNMP docker upgrade to stretch build

---

sonic_platform_base/sonic_sfp/sff8436.py
sonic_platform_base/sonic_sfp/sff8472.py
sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sfputilbase.py

This change is added to dump ChannelMonitor Threshold and Module Monitor Threshold values as part of DOM EEPROM dump output.
Added code change in sff8436.py,sfputilshow.py, xcvrd,  sfpshow .. etc
Verified the output in following optics
a) AVAGO
b) Finisar
c) DELL
Seeing the following issue of Values not getting dumped properly from day 1
Some channel monitor values are not displayed correctly.
Will raise a seperate issue for that.
Ethernet124: SFP EEPROM detected
Connector: MPOx12
Encoding: 64B66B
Extended Identifier: Power Class 1(1.5W max)
Extended RateSelect Compliance: QSFP+ Rate Select Version 1
Identifier: QSFP+ or later
Length OM3(2m): 50
Nominal Bit Rate(100Mbs): 103
Specification compliance:
10/40G Ethernet Compliance Code: 40GBASE-SR4
Vendor Date Code(YYYY-MM-DD Lot): 2010-09-01 …

sonic_sfp: Support for DOM Threshold values for EEPROM dump

---

sonic_platform_base/chassis_base.py
sonic_platform_base/module_base.py

Add base class for firmware management API
(https://github.com/Azure/sonic-buildimage/pull/3013)
Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com

[sonic_platform_base/chassis_base]: Add firmware management interface

---

sonic_platform_base/chassis_base.py

- This will make reporting the reboot cause to the user easier, as we can use these strings directly

[ChassisBase] Make reboot cause constant strings human-readable

---

sonic_sfp/sfputilbase.py

This is part of PR#31 of sonic-platform-daemons, there could be a key error
in get_physical_to_logical() in SFP monitor due to a timing issue, and
it will later be recovered automatically.
Signed-off-by: Dante (Kuo-Jung) Su <dante.su@broadcom.com>

sonic_sfp: avoid possible key error in get_physical_to_logical()

---

sonic_platform_base/sonic_sfp/sff8436.py
sonic_sfp/sff8436.py

support the following fields in sff8436:
dom_control_bytes_masks which represents the "7.6.1.5 Control Bytes", for disabling tx on a per-channel basis.
dom_option_value_masks which represents the "7.6.2.23 Options", for testing whether per-channel basis tx-disable is supported on the module.
support InitCompleteFlag.

[sff8436] support "Control Bytes" and "Options"

---

sonic_sfp/sfputilbase.py

There was a problem with the abbreviated type name fetching if the xcvr
was OSFP. This commit fixes the issue.
Previously,
`transceiver_info_dict['type_abbrv_name'] = sfp_type_data['data']['type_abbrv_name']['value']`
would fail.

Fix abbrv name for OSFP

---

sonic_platform_base/fan_base.py
sonic_platform_base/psu_base.py

- Also add the same function to fan_base.py.

[psu_base] get_status_led() returns current state of the status LED

---

sonic_sfp/sff8436.py

1. add type_abbrv_name handling which was removed inadvertently in PR #38 from sonic_sfp/sff8436.py

readd type_abbrv_name in sonic_sfp/sff8436.py

---

sonic_platform_base/sonic_sfp/sfputilbase.py

Extend the return of the function to make the function can return some system-level event/error.
like the system not ready, the system becomes ready and the system fails.
By getting these new events upper layer apps(xcvrd) will have more awareness of the system status and handle accordingly.   These events are not mandatory,  vendors can choose to not implement this and xcvrd will not be impacted.

[sfputilbase] Extend get_transceiver_change_event return event

---

sonic_platform_base/sonic_sfp/sffbase.py

In get_transceiver_info_dict() an exception is generated on access to sfp_interface_bulk_data element that was not added in case SFP EEPROM 'int' value was zero. Actually, zero should be valid value as well.
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

[sonic_sfp] Interpret sff 'int' element =0 as valid value

---

sonic_platform_base/sonic_sfp/sfputilbase.py

- Added default cable_type and cable_length.
From SFF-8436 regarding cable length fields:
"A value of zero means that the Module does not support [this mode] or that the length information must be determined from the Module technology."
It is possible that all cable length fields in eeprom are 0, and this would lead to xcvrd crashing due to fetching of this data. Fallback is added in this case.

[xcvrd] Fix crashing due to missing fields of some module types

---

sonic_sfp/sfputilbase.py

fix syntax error in sfputilbase._read_eeprom_specific_bytes

[sonic_sfp] fix syntax error in sfputilbase._read_eeprom_specific_bytes

---

sonic_platform_base/sfp_base.py

Exceptions should be raised, not returned.

[sfp_base] Raise NotImplementedError exceptions instead of returning them

---

sonic_platform_base/chassis_base.py
sonic_platform_base/component_base.py
sonic_platform_base/module_base.py

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
The purpose of these changes are:
* Improve component API scalability
* Avoid code duplication: both chassis_base.py and module_base.py share the same methods:  
_get_component_name_list(), get_firmware_version(), install_component_firmware()_
* Add new description field (later will be used by fwutil):  
_get_description()_

Added new API to interact with the platform components

---

setup.py
sonic_platform_base/sonic_ssd/ssd_base.py
sonic_platform_base/sonic_ssd/ssd_generic.py

Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>

Add SSD Health API and generic implementation

---

sonic_platform_base/sonic_sfp/sfputilbase.py

In __get_transceiver_dom_threshold_info_dict()__ ad a case to handle osfp port type.
In get_transceiver_info_dict() update __specification_compliance__ from N/A to empty dictionary.
This prevents error in _sfpshow_ trying to prase data from STATE_DB with _eval_ function.

[sfputilbase] Fix xcvr and sfpshow crash with OSFP

---

sonic_platform_base/chassis_base.py
sonic_platform_base/module_base.py
sonic_platform_base/psu_base.py

… the base class
When we use a mutable object as a default value in the base class, a value that can be modified in place in the subclasses, such as the empty lists of
the chassis base class, and it is most likely unwanted.
And hence, this commit will try to address this issue by allocating new empty
list objects at the constructor of the base class, and the subclass should
rely on the constructor of superclass for this.
As a result, it simplifies the source code, and reduce the maintenance efforts
Signed-off-by: Dante (Kuo-Jung) Su <dante.su@broadcom.com>

[sonic_platform_base] Reallocate empty lists in the constructor of the base class

---

sonic_platform_base/fan_base.py

[sonic_platform_common/fan]add fan direction "not applicable"
it is for the devices that don't support fetching fan's direction for now

[sonic_platform_common/fan]add fan direction "not applicable"

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
Summary:
Add EEPROM DB Checksum field:
```bash
root@sonic:/etc/sonic# redis-cli -n 6 KEYS '*' | grep EEPROM
EEPROM_INFO|0x25
EEPROM_INFO|0x28
EEPROM_INFO|0x22
EEPROM_INFO|0x2b
EEPROM_INFO|0x2a
EEPROM_INFO|State
EEPROM_INFO|0x24
EEPROM_INFO|0x29
EEPROM_INFO|TlvHeader
EEPROM_INFO|0xfd
EEPROM_INFO|0x21
EEPROM_INFO|0x23
EEPROM_INFO|0x26
EEPROM_INFO|Checksum
root@sonic:/etc/sonic# redis-cli -n 6 HGETALL 'EEPROM_INFO|Checksum'
1) "Valid"
2) "1"
```
Old version:
```bash
root@sonic:/etc/sonic# decode-syseeprom -d
TlvInfo Header:
Id String:    TlvInfo
Version:      1
Total Length: 595
TLV Name             Code Len Value
-------------------- ---- --- -----
...
CRC-32               0xFE   4 0x9A9E52B0
```
New version:
```bash …
```

[eeprom]: Add DB checksum field

---

setup.py
sonic_thermal/thermal_base.py

**What I did**
Add an abstract class for thermal plugin
**How I did it**
Add the following interfaces for thermal plugin
- get_num_thermals
- get_name
- get_temperature
- get_low_threshold
- get_low_critical_threshold
- get_high_threshold
- get_high_critical_threshold

[sonic_thermal]Add abstract class for thermal plugin

---

sonic_fan/fan_base.py

**- What I did**
Add string constants for fan directions
**- How I did it**

[sonic_fan]Add constant for fan direction

---

sonic_platform_base/sonic_thermal_control/thermal_json_object.py
sonic_platform_base/sonic_thermal_control/thermal_manager_base.py
sonic_platform_base/sonic_thermal_control/thermal_policy.py

Add validation for thermal policy file:
1. validate duplicate/empty thermal condition
2. validate duplicate/empty thermal policy
3. validate thermal policy with same condition but different actions

[Mellanox] Add validation for thermal policy 

---

sonic_platform_base/sonic_sfp/sff8472.py
sonic_platform_base/sonic_sfp/sfputilbase.py

SFP(sff8472 attributes) transciever eeprom attribute support.
```
Nov  5 14:32:52.721493 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1077, in <module>
Nov  5 14:32:52.723223 sonic INFO pmon#supervisord: xcvrd     main()
Nov  5 14:32:52.723775 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1074, in main
Nov  5 14:32:52.724157 sonic INFO pmon#supervisord: xcvrd     xcvrd.run()
Nov  5 14:32:52.724486 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1038, in run
Nov  5 14:32:52.724836 sonic INFO pmon#supervisord: xcvrd     self.init()
Nov  5 14:32:52.725176 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1022, in init
Nov  5 14:32:52.725539 sonic INFO pmon#supervisord: xcvrd …
```

SFP(sff8472 attributes) transciever eeprom attribute support.

---

sonic_platform_base/sonic_sfp/sfputilbase.py

Detect an SFP adapter in a QSFP port, and instantiate an SFP object instead of a QSFP object.
Signed-off-by: Howard Persh <Howard_Persh@dell.com>

sonic_sfp: QSA support

---

sonic_platform_base/component_base.py

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
**Summary:**
The purpose of this PR is to propagate some new component firmware management APIs which are intended to make the process more versatile. These new API's will be used mostly to extend `fwutil` functionality in order to support new platform components (e.g, SSD).
**Motivation:**
1. Inform user in advance about required component firmware update actions when operating in manual mode
2. Allow `fwutil` to read component firmware version directly from image instead of configuration file if not provided

[component]: Introduce new firmware management API

---

sonic_platform_base/chassis_base.py
sonic_platform_base/fan_drawer_base.py

What I did:
1. Add an abstract class FanDrawerBase
2. Modify existing ChassisBase class to hold a list of FanDrawerBase objects

[Mellanox] add abstract FanDrawerBase class to support fan drawer in platform API

---

sonic_platform_base/psu_base.py

Add four new platform API to PsuBase:
1. get_temperature
2. get_temperature_high_threshold
3. get_voltage_high_threshold
4. get_voltage_low_threshold

[psu_base] Add new platform APIs to support PSU LED management

---

sonic_platform_base/component_base.py

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
**Summary:**
The purpose of this PR is to propagate some new component firmware management APIs which are intended to make the process more versatile. These new API's will be used mostly to extend fwutil functionality in order to support new platform components (e.g, SSD).
**Motivation:**
1. Inform user in advance about required component firmware update actions when operating in manual mode
2. Allow fwutil to read component firmware version directly from image instead of configuration file if not provided

[201911][component]: Introduce new firmware management API

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Signed-off-by: Sangita Maity <sangitamaity0211@gmail.com>
> [Azure/sonic-utilities/pull/767](https://github.com/Azure/sonic-utilities/pull/767) PR in **_sonic_utilities_** submodule(filename: [sfputil/main.py](https://github.com/Azure/sonic-utilities/pull/767/files) depends on this PR.
All three PRs are necessary to run `show interfaces transceiver` command.
1. [Azure/sonic-buildimage#3912](https://github.com/Azure/sonic-buildimage/pull/3912)
2. [Azure/sonic-platform-common#72](https://github.com/Azure/sonic-platform-common/pull/72)
3. https://github.com/Azure/sonic-utilities/pull/767
Add support of platform.json in **_sfputilbase_** and **_sfputilhelper_** file. Code is duplicated in **_sfputilhelper_** file as sfputilbase is an abstract base class. So, it cant be instantiated.
``` …
```

[sfputilbase | sfputilhelper] Add support of platform.json

---

sonic_platform_base/sonic_sfp/sfputilbase.py

What I did:
Remove undefined variable 'sysfs_sfp_i2c_client_eeprom_path'
Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>

[sfputilbase.py] Don't try to print EEPROM sysfs file name if we failed to read from it

---

sonic_platform_base/chassis_base.py

To support system health feature, we need get/set system LED status.
How I did this?
Add 2 new platform API to chassis_base.py for vendor to implement:
- set_status_led
- get_status_led

[chassis_base] Add platform API support for system LED

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Fix typo:  portconfig.ini to port_config.ini
The typo is introduced by https://github.com/Azure/sonic-platform-common/commit/4040326948d334b774daf4b6495f096e251442f1

[sfputil] fix typo:  portconfig.ini to port_config.ini

---

sonic_platform_base/sfp_base.py
sonic_platform_base/sonic_sfp/sfputilbase.py

Change the following key names:
- hardwarerev -> hardware_rev
- serialnum -> serial
- manufacturename -> manufacturer
- modelname -> model
- Connector -> connector
Also fix a typo and some return types in docstrings

[sfp] Tweak key names of some transceiver info fields

---

sonic_platform_base/sfp_base.py

Update docstrings of `get_rx_los()`, `get_tx_fault()` and `get_tx_disable()` methods to reflect that they should return a list of values where each value reflect the status of an individual SFP channel. Also add more detail to other channel-specific method docstrings.

[sfp_base] Update return value documentation of channel-specific methods

---

sonic_platform_base/sonic_sfp/sfputilhelper.py

The SfpUtil interface used in xcvrd expects get_physical_to_logical to return None in the case of unknown port:
https://github.com/Azure/sonic-platform-daemons/blob/master/sonic-xcvrd/scripts/xcvrd#L906
Note SfpUtilBase implementation already conforms the interface in xcvrd:
https://github.com/Azure/sonic-platform-common/blob/master/sonic_platform_base/sonic_sfp/sfputilbase.py#L603

[sfputil] Make SfpUtilHelper.get_physical_to_logical noexcept as in SfpUtilBase

---

sonic_platform_base/sfp_base.py

Fix key name typo: "mominal_bit_rate" -> "nominal_bit_rate"

[SfpBase] Fix key name typo in docstring

---

sonic_fan/fan_base.py
sonic_psu/psu_base.py

Small changes in 1.0 platform plugins psu_base.py and fan_base.py. Changes are related to PDDF 2.0 changes. 
psu_base.py:
- psu_fan speed API name change 
- Changing the voltage, current and power units to 
fan_base.py:
- Individual fans are counted instead of fantrays units
- get_speed_rear() is not required
Depends on:
https://github.com/Azure/SONiC/pull/536

Changes in fan and psu base classes (1.0 platform API) related to pddf_2.0

---

sonic_platform_base/sonic_pcie/pcie_common.py

Updated get_pcie_check() to use sysfs entry check instead of lspci output for the pcie device status check.
Changed the line endings from Windows to Unix and removed all tailing spaces.

update get_pcie_check() to use sysfs instead of lspci output

---

sonic_platform_base/sonic_sfp/sfputilbase.py

Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>
Fixes the following bug reproduced on SONiC.HEAD.729-dirty-20200727.075328:
```
pmon#supervisord: xcvrd Traceback (most recent call last):
INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1207, in <module>
INFO pmon#supervisord: xcvrd     main()
INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1204, in main
INFO pmon#supervisord: xcvrd     xcvrd.run()
INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1165, in run
INFO pmon#supervisord: xcvrd     self.init()
INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1144, in init
INFO pmon#supervisord: xcvrd     post_port_sfp_dom_info_to_db(is_warm_start, self.stop_event)
INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 430, in …
```

[sfputilbase.py] Add application_advertisement N/A field to transceiver_info_dict for platform api 1.0

---

sonic_platform_base/sonic_sfp/qsfp_dd.py

Add a leading '.' to import a file in the same folder,  or python3 wheel building will fail.

[bug fix] fix import issue for python3 whl building

---

setup.py
sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

As part of consolidating all common Python-based functionality into the new sonic-py-common package, this pull request migrates from importing the sonic-daemon-base package to importing the sonic-py-common package. This is the next step toward resolving https://github.com/Azure/sonic-buildimage/issues/4999.
- Also reorganize imports for consistency

Migrate from sonic-daemon-base package to sonic-py-common package

---

setup.py

Currently, we are building both Python 2 and Python 3 versions of sonic-platform-common. However, we are currently not creating a Python 3 version of sonic-config-engine, so the build breaks. As I intend to remove this dependency in the near future anyway, I am removing it.

Remove sonic-config-engine dependency from setup.py

---

sonic_platform_base/sonic_sfp/sff8436.py

Previously  'Extended Specification compliance' was added as part of "sfp_info_bulk", this will request all the vendors to update the related platform API implementation due to the width change of  "sfp_info_bulk". 
To avoid this, make it parsed separately, it will not impact vendors who haven't update the platform API implementation.

Parse 'Extended Specification compliance' as independent field

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

This is for changes needed to support multi-asic platforms. 
(i) Add a new API to parse the port_config.ini files in different directories named based on the asic_ID's 
(ii) Add a new dictionary which maps the interface to the asic_id 
(iii) Check if it is a backplane interface, if so skip from adding it to logical_port list

Sfputil base and helper class changes for multi-ASIC

---

sonic_platform_base/sonic_sfp/sff8472.py

Alpha chars in hex-based keys should be lowercase.
Resolves: https://github.com/Azure/sonic-platform-common/issues/114

[sff8472.py] Make hex keys all lowercase

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Signed-off-by: Sangita Maity <sangitamaity0211@gmail.com>
**Before this fix**
sfputilbbase and sfputilhelper were not able to unpack the value correctly as `get_port_config` function was returning three variables including the new port_alias_map dictionary. 
```
admin@lnos-x1-a-asw02:~$ show interfaces transceiver lpmode
Error reading port info (too many values to unpack)
```
**After the fix**
```
admin@lnos-x1-a-asw02:~$ show interfaces transceiver lpmode --verbose
Command: sudo sfputil show lpmode
Port         Low-power Mode
-----------  ----------------
Ethernet0    Off
Ethernet1    Off
Ethernet2    Off
Ethernet3    Off
Ethernet4    Off
Ethernet5    Off
Ethernet6    Off
Ethernet7    Off
Ethernet8    Off
Ethernet9    Off
```
- Which release branch to backport (provide reason below if …

[sfputilbase|sfputilhelper] fix value unpack error due to port_alias_map in portconfig.py file

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Commit for PR (https://github.com/Azure/sonic-platform-common/pull/100) into 201911 branch

[201911] multi-asic changes for sfputil 

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Remove the use of constant PORT_CONFIG_INI in 201911 in sonic_sfp.  
This is a follow up commit to the earlier 201911 commit https://github.com/Azure/sonic-platform-common/pull/117 ( double commit of https://github.com/Azure/sonic-platform-common/pull/100 in master )

[201911] [ multi-asic] Remove the use of constant PORT_CONFIG_INI in sonic_sfp

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Signed-off-by: Sangita Maity <sangitamaity0211@gmail.com>
**Before this fix**
XCVRD was not working fine. 
```
Aug  6 19:06:12.026264 falco-test-dut01 INFO pmon#xcvrd: Start daemon init...
Aug  6 19:06:12.384054 falco-test-dut01 INFO pmon#xcvrd: chassis loaded <sonic_platform.chassis.Chassis object at 0x7f53ecbe9f50>
Aug  6 19:06:15.294866 falco-test-dut01 INFO pmon#xcvrd: xcvrd: No media file exists
Aug  6 19:06:15.296448 falco-test-dut01 INFO pmon#xcvrd: Wait for port config is done
Aug  6 19:06:15.302478 falco-test-dut01 INFO pmon#xcvrd: Post all port DOM/SFP info to DB
Aug  6 19:06:15.306300 falco-test-dut01 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Aug  6 19:06:15.306541 falco-test-dut01 INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 1083, in …
```

Fix fp_port_index error to get correct index type

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

Add a new function to TlvInfoDecoder which can return device part number as a string.

[EEPROM] Add new function part_number_str to TlvInfoDecoder

---

sonic_platform_base/chassis_base.py
sonic_platform_base/module_base.py

ChassisBase and ModuleBase inherit from the DeviceBase class, which already provides a `get_serial()` method. Thus, these methods were redundant.

[ChassisBase][ModuleBase] Remove redundant 'get_serial_number()' method

---

sonic_platform_base/fan_drawer_base.py

Summary:
This PR adds the definition of get_fan api for fan_drawer base class, since it was missing for base_class definitions. 
It takes an index parameter and returns the appropriate fan instance of fan_base class. 
Added definition of the api in the sonic_platform_base directory of sonic-platform-common. 
To improve platform_api of fan_drawer class
Added definition of the api in the sonic_platform_base directory of sonic-platform-common. 
Nothing to verify, since this is a base class definition

[sonic_platform_base][fan_drawer_base] adding get_fan definition to the base api definitions of fan_drawer base class

---

sonic_platform_base/fan_drawer_base.py

Fix the new definition of get_fan in fan_drawer_base.py

[sonic_platform_base] fix an indentation in fan_drawer_base.py

---

sonic_y_cable/y_cable.py

Summary:
This PR fixes the unpacking of the bytes returned via the read_eeprom API of SfpBase class. This replaces interpretation of bytes returned by read_eeprom as an integer to a single unsigned byte, since all read_eeprom API's read single byte for now inside sonic_y_cable package, and interpreting it as an integer would require 4 bytes atleast. We also add missing SYSLOG_IDENTIFIER for y_cable
Added changes in the sonic_y_cable directory of sonic-platform-common
To configure the Credo Y cable through the Platform API's, the sonic_y_cable package has to work correctly. 
Added the changes to the y_cable.py file. 
Nothing to verify, since read/write eeprom API's are not available. 
Platform must have optoe driver support for  instantiation of sysfs/eeprom 
read/write Platform API's must …

[SONIC_Y_CABLE] Fix unpacking of the result returned from read_eeprom API and add missing syslog identifier

---

sonic_platform_base/device_base.py
sonic_platform_base/psu_base.py
sonic_platform_base/sfp_base.py

In order to implement physical entity mib object entPhysicalParentRelPos, entPhysicalContainedIn and entPhysicalIsFRU, new platform API is required to collect information from each vendor.
What I did?
1. Add DeviceBase.is_replaceable and DeviceBase.get_position_in_parent
2. Add PsuBase.get_num_thermals, PsuBase.get_all_thermals, PsuBase.get_thermal
3. Add SfpBase.get_num_thermals, SfpBase.get_all_thermals, SfpBase.get_thermal

[sonic-platform-common] Add new platform API for SONiC Physical MIB Extension feature

---

sonic_platform_base/sfp_base.py
sonic_platform_base/sonic_sfp/sffbase.py

Summary:
This PR defines the base class methods for reading and writing eeprom address space, which is going to be utilized by 
xcvrd and cli for as a part of mux driver implementation for the Credo Y cable. With this change vendors will have to implement these api's as a part of SFP's since they inherit sffbase class which in turn will provide the upper layers to be able to read/write the sysfs eeprom address space
Added changes in the sonic_sfp directory of sonic-platform-common
To configure the Credo Y cable through the Platform API's which is the fundamental for dual TOR support for SONIC
Added the API's with the abstract definitions 
for the basic configurations/capabilities of Credo Y cable within sfputilbase.py
Nothing to verify
Platform must have optoe driver support for …

[SONIC_SFP] adding abstract methods for reading and writing the eeprom address space within platform api

---

.gitignore
pytest.ini
setup.cfg
setup.py
tests/read_port_mappings_test.py
tests/sfputilhelper_test.py
tests/t0-sample-port-config.ini

Summary:
This PR provides the necessary infrastructure to add pytest support and integration in sonic-platform-common submodule.
This PR also adds the read_port_mappings_test as a pytest
Added changes in the setup.py and setup.cfg and initialized the tests directory
new file:   setup.cfg
modified:   setup.py
new file:   tests/__init__.py
new file:   tests/read_port_mappings_test.py
new file:   tests/t0-sample-port-config.ini
To add the pytest support in sonic-platform-common
Added the changes in sonic-platform-common module
run the test a part of 
make target/python-wheels/sonic_platform_common-1.0-py2-none-any.whl
make target/python-wheels/sonic_platform_common-1.0-py3-none-any.whl

Add unit test infrastructure

---

sonic_platform_base/sonic_eeprom/eeprom_base.py
sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

The `string` type has changed between Python 2 and 3. Therefore, the Python 3 version of this library is broken.
This PR changes the data type of the raw EEPROM data to a `bytearray`, which is treated the same in both Python 2 and Python 3, and is technically a more appropriate data type for the raw bytes anyway.
However, this PR could cause issues if any vendors are overriding the `read_eeprom_bytes()` or `read_eeprom()` functions and returning a `string`. Any vendors doing so will need to refactor their implementation to return a `bytearray` instead.

[sonic_eeprom] Make compatible with Python 2 and 3

---

sonic_platform_base/chassis_base.py
sonic_platform_base/device_base.py
sonic_platform_base/fan_drawer_base.py
sonic_platform_base/module_base.py
sonic_platform_base/psu_base.py

sonic-platform-base: Changes to introduce APIs for modular chassis for power-consumption and supplied
HLD: Azure/SONiC#646
PSUd APIs for power requirement calculations
get_maximum_supplied_power() - per PSU
get_status_master_led() - get master psu led status. Class method.
set_status_master_led() - set master psu led status. Class method.
get_maximum_consumed_power(self) - per consumer API. Consumers are modules, Fans

Common power consumption and supply APIs for modular chassis

---

sonic_platform_base/psu_base.py

Member constant is inherited; do not need to reference into base class.

[PsuBase] Reference inherited member constant

---

sonic_platform_base/psu_base.py
sonic_platform_base/sonic_sfp/qsfp_dd.py

Found name error and import error when testing with python3 pmon daemons
How I fix this?
1. Fix name error in psu_base.py
2. change absolute import to relative import for sff8024

[sonic-platform-common] Fix name error and import error 

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
Fix crash in `show version` CLI command:
```
admin@sonic:~$ show version 
SONiC Software Version: SONiC.master.39-dirty-20201116.030425
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: e526d889
Build date: Mon Nov 16 06:49:50 UTC 2020
Built by: johnar@jenkins-worker-4Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot
File "/usr/local/bin/decode-syseeprom", line 171, in <module>
exit(main())
File "/usr/local/bin/decode-syseeprom", line 47, in main
t = class_('board', '','','')
File "/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/plugins/eeprom.py", line 104, in __init__
if self.eeprom_init():
File …
```

[sonic_eeprom] Fix variable type

---

sonic_y_cable/y_cable.py

Summary:
This PR provides the support for error checking the returned values from eeprom read for sonic_y_cable, particularly if garbage/non expected value/values are returned. 
added the changes in sonic_y_cable/y_cable.py file
support for error checking the returned values from eeprom read for sonic_y_cable, particularly if garbage/non expected values are returned. 
added code after read_eeprom api's to validate the returned values. 
Ran the pmon docker with the changed file .

[sonic_y_cable] support for error handling non-expected eeprom_read return values inside sonic_y_cable

---

sonic_platform_base/sonic_eeprom/eeprom_base.py

Close EEPROM lock file after unlocking. Python 3 now outputs warnings such as the following to stderr if a file descriptor is left open:
```
/usr/local/bin/decode-syseeprom:171 : ResourceWarning : unclosed file <_io.TextIOWrapper name='/var/run/hw-management/eeprom/vpd_info' mode='r' encoding='UTF-8'>
```
With this change, the above warning is no longer displayed.

[eeprom_base] Close lock file after unlocking

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

From this change https://github.com/Azure/sonic-platform-common/pull/100 , It missing mapping of logical port names to ASIC instance on device that used platform.json
So this new change will fix it by add logical_to_asic mapping dict to a condition for device that used _platform.json_
**Signed-off-by**: Wirut Getbamrung [wgetbumr@celestica.com]

[sonic_sfp]: Update config for multi-ASIC

---

sonic_platform_base/chassis_base.py
sonic_platform_base/module_base.py

sonic-platform-base: Midplane monitoring APIs module_base.py and chassis_base.py for modular chassis
HLD: Azure/SONiC#646
- What I did
Enhance ModuleBase with new APIs to get midplane-ip-address and check-rechability
Enhance ChassisBase with new API to initialize the midplane for modular chassis
- How I did it
Add API in chassis_base.py:
```
init_midplane_switch()
```
Add APIs in module_base.py
```
get_midplane_ip()
is_midplane_reachable()
```

Modular Chassis - Midplane monitoring APIs

---

sonic_y_cable/y_cable.py

Summary:
This PR provides the support for checking the mux_direction on the y_cable by checking the mux_direction register
added the changes in y_cable.py with register specification for check_mux_direction
check_mux_direction is required for y_cable_utilities to replace the active_linked_tor_side -> check_mux_direction as agreed as a part of design
added the API definition
Ran the pmon docker with the changed file, and redis-cli to obtain the events and check the functionality is working, also confirmed the same with i2c commands by toggling the mux

[sonic_y_cable] add check_mux_direction api for y_cable

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

Fix errors like below:
```
admin@sonic:~$ show version 
SONiC Software Version: SONiC.master.0-dirty-20201204.005739
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 873fb969
Build date: Fri Dec  4 09:02:43 UTC 2020
Built by: user@sonic-build
Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot
File "/usr/local/bin/decode-syseeprom", line 171, in <module>
exit(main())
File "/usr/local/bin/decode-syseeprom", line 47, in main
t = class_('board', '','','')
File "/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/plugins/eeprom.py", line 113, in __init__
if self.eeprom_init():
File "/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/plugins/eeprom.py", line 180, in eeprom_init
self, "", [eeprom_params])
File …
```

Make eeprom_tlvinfo.py Python3 compatible

---

sonic_y_cable/y_cable.py

When build python3 xcvrd, it tries to do basic check which will import this y_cable.py. However, not all platform supports python3 API now, so it could cause an issue when importing sonic_platform.platform. See error:
```
10:03:13  Modified dependencies are : [sonic_py_common-1.0-py3-none-any.whl sonic_xcvrd-1.0-py2-none-any.whl sonic_platform_common-1.0-py3-none-any.whl  M  rules/sonic-xcvrd.dep M  rules/sonic-xcvrd.mk M  slave.mk M  sonic-slave-buster/Dockerfile.j2   M  setup.py M  xcvrd/xcvrd.py M  xcvrd/xcvrd_utilities/y_cable_helper.py ] 
10:03:13  /sonic/src/sonic-platform-daemons/sonic-xcvrd /sonic
10:03:13  running test
10:03:13  WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point …
```

[y_cable] Skip ImportError in y_cable.py

---

sonic_platform_base/sonic_sfp/sffbase.py

Change sffbase.py code to make it compatible with python3
How I did this?
1. change iteritems to items
2. change type(*) = types.* to type(*) = $typename
How I test this?
Run regression

[sffbase.py] Fix to make Python 3-compatible

---

sonic_platform_base/sonic_sfp/sfputilbase.py

Make `_read_eeprom_specific_bytes` Python3 and Python2 compatible

Make sonic_sfp Python2 and Python3 compatible

---

sonic_platform_base/sonic_pcie/pcie_base.py
sonic_platform_base/sonic_pcie/pcie_common.py

- Introduce a new platform API `get_pcie_aer_stats` in class `PcieBase` for retrieving AER stats of a PCIe device.
- Add common implementation of `get_pcie_aer_stats` in class `PcieUtil`
Ref: Azure/SONiC#702

[sonic_pcie] Add get_pcie_aer_stats and its common implementation

---

sonic_platform_base/sonic_sfp/sff8436.py
sonic_platform_base/sonic_sfp/sff8472.py
sonic_platform_base/sonic_sfp/sfputilbase.py

- What I did
Following SFF-8472 to read diagnostic monitoring type register.
Use that register to check if diagnostic monitoring function implemented or not.
- How I did it
Check the register position from SFF-8472 document.
Read the register value from the EEPROM.
- How to verify it
Compare one transceiver which support diagnostic monitoring function to another transceiver which doesn't support it.
Run 'show interfaces transceiver eeprom' command.

[sfp] Add parsing the dom_capability to sff8472

---

sonic_y_cable/y_cable.py

Summary:
This PR provides the necessary infrastructure to add support for measuring BER (Bit error rate) and Eye scan and also 
run different modes on the Cable - PRBS and Loopback. 
Added changes in the sonic_y_cable package
To add the necessary support for measuring BER and EYE scan, and run PRBS/Loopback modes on the Y cable 
Added the changes in sonic-platform-common module in the y_cable.py file
opened a python shell and ran the API's manually and test verified
the values are correct.

[sonic_y_cable] Add support for measuring BER and EYE scan and running Loopback, PRBS modes on the Y cable

---

sonic_platform_base/component_base.py

To support the component firmware automatic update, add auto_update_firmware() to platform component api
This is to support fwutil auto_update command to update  the platform component firmware automatically.
Fwutil HLD to support auto_update interfaces/commands.
https://github.com/Azure/SONiC/pull/648

[component] add auto_update_firmware() to support the auto update.

---

azure-pipelines.yml

Call pip2/3 using sudo to ensure packages are installed globally.

[ci] Call pip2/3 using sudo

---

sonic_platform_base/sonic_sfp/qsfp_dd.py

Update method name to align with other drivers. Change from `parse_qsfp_dom_capability` to `parse_dom_capability`. Other drivers were aligned via https://github.com/Azure/sonic-mgmt/pull/2937.
When this submodule is updated in sonic-buildimage, all callers will need to be updated to reflect the new nomenclature.

[sonic_sfp/qsfp_dd.py] Update DOM capability method name to align with other drivers

---

sonic_platform_base/sonic_sfp/sffbase.py

When called with Python 3, `str.strip(binascii.unhexlify(ret_str))` will raise an exception: ` descriptor 'strip' requires a 'str' object but received a 'bytes'`. This patch (`binascii.unhexlify(ret_str).decode("utf-8").strip()`) will work properly with both Python 2 and Python 3.
Fixes https://github.com/Azure/sonic-platform-common/issues/160

[sffbase] Make convert_hex_to_string() compatible with both Python 2 and Python 3

---

sonic_y_cable/y_cable.py

This PR adds a stub function definition with details as to how it should be implemented by a Y cable vendor. 
Added a stub function definition with a doc string describing how it should be implemented
Cleaning up and split some API's for vendors
Firmware upgrade is a functionality that vendors need to implement, this PR adds the definition 
and a description of how the implementation of this firmware_upgrade  API should be 
Will be tested once implemented
for cleanup API's opened a python shell and executed API's for correctness

[sonic_y_cable] add stub function for upgrade firmware of Y cable and split the get_part_number and get_vendor API's

---

sonic_y_cable/y_cable.py

This PR adds stub functions definition with details as to how firmware upgrade should be implemented by a Y cable vendor. 
It also fixes the read_eeprom read size for vendor part number and vendor name retreival API's
Added a stub functions definition with a doc string describing how it should be implemented
Added these API's stub functions for vendors to implement
```
def download_firmware(physical_port, fwfile)
def activate_firmware(physical_port)
def rollback_firmware(physical_port)
```
Firmware upgrade is a functionality that vendors need to implement, this PR adds the definition's
and a description of how the implementation of this firmware upgrade  procedure API's should be implemented
by breaking down the firmware upgrade into above specified sub routines.
Will be tested once …

[y_cable] refactor upgrade firmware API's; Fix vendor and part number API's read size for read_eeprom

---

sonic_platform_base/fan_drawer_base.py

Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>
Fix api to conform the description

[fan_drawer_base.py] Fix FanDrawer get_status_led interface

---

sonic_y_cable/y_cable.py

This PR adds functions definition with details for enabling/disabling Y cable auto-switch feature
Added functions for enabling/disabling auto-switch on Y cable
```
def set_switching_mode(physical_port, mode)
def get_switching_mode(physical_port)
```
We need to have this feature within host cli so that a user can enable/disable the autoswitch on Y cable
opened a python shell and executed API's for correctness

[y_cable] add support for enable/disable autoswitch feature on Y cable

---

sonic_platform_base/thermal_base.py

Signed-off-by: d-dashkov <Dmytro_Dashkov@Jabil.com>
Two new functions have been added to thermal_base.py for setting critical temperature thresholds.
fixes https://github.com/Azure/sonic-buildimage/issues/6241

[thermal_base] Add setter functions for critical thresholds

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_y_cable/y_cable.py

- Change import order in Ycable helper
- Change data read from EEPROM to bytearray in _read_eeprom_specific_bytes for python 2 and 3 compatibility.
https://github.com/Azure/sonic-buildimage/issues/6820
- Import of sonic_platform before logger when platform API is not available leads to non import of logger resulting in xcvrd crash
- Since string and byte comparison returns true in python2 current check for differentiating python2 and 3 in EEPROM read fails.
Verified that python 2 xcvrd runs without exiting in DellEMC S5248F platform.
Logs: [Unit testing logs.txt](https://github.com/Azure/sonic-platform-common/files/6123278/Unit.testing.logs.txt)

Change import order in Ycable helper and EEPROM read bytearray change in SFP plugin

---

sonic_y_cable/y_cable.py

Signed-off-by: Lawrence Lee <lawlee@microsoft.com>
Use the `@hook_y_cable_simulator` decorator for all methods in `y_cable.py`
Decorating all methods (including those that read from hardware) allow us to mock these methods in the mux simulator client and prevent XCVRD from generating errors when run with the mux simulator.
Copied changes to a dual ToR testbed with mux simulator, verified normal operation.

[sonic_y_cable]: Decorate all method for mux simulator

---

sonic_y_cable/y_cable.py

This PR refactors the get_firmware_version output to return the following fields for each target. 
```
{
"version_active": "",
"version_inactive": "",
"version_next": "",
```
So by calling this for all the 3 MCU's TOR1, TOR2 and NIC we can get the below result. 
```
{
"version_nic_active": "0.6MS",
"version_nic_inactive": "0.5MS",
"version_nic_next": "0.6MS",
"version_self_active": "0.5MS",
"version_self_inactive": "0.6MS",
"version_self_next": "0.6MS",
"version_peer_active": "0.6MS",
"version_peer_inactive": "0.6MS",
"version_peer_next": "0.6MS",
} 
```
Required to refactor get_firmware_version output to comply with all vendors output.

[Y-Cable] refactor get_firmware_version to comply with all vendors

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Inband port is avaialable in PORT table. But regular port handlings are
not applicable for Inband port. Changes in this PR for avoiding regular
port handling on Inband port.
This PR depends on sonic-buildimage PR https://github.com/Azure/sonic-buildimage/pull/6477

[voq/inbandif] Voq inbandif port

---

sonic_platform_base/device_base.py

Added a `get_revision()` method to the generic platform device class which returns the hardware revision number of the device as a string. 
Exposing the hardware revision number to the platform API allows the user to precisely determine the FRU hardware components installed for debugging and inventory tracking purposes.

 [DeviceBase] Added hardware revision number to generic device properties

---

sonic_platform_base/sonic_thermal_control/thermal_manager_base.py
tests/thermal_manager_test.py
tests/thermal_policy.json

Add a stop function to thermal manager
Allow thermalctld to call the stop function to stop run_policy function fast
sonic-mgmt regression

[thermal_manager_base] Add a stop function to thermal manager

---

sonic_platform_base/sonic_sfp/qsfp_dd.py

xcvrd crashes with the following trace for few media when processing application advertisement.
File "/usr/local/bin/xcvrd", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1415, in main
xcvrd.run()
File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1363, in run
self.init()
File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1328, in init
post_port_sfp_dom_info_to_db(is_warm_start, self.stop_event)
File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 501, in post_port_sfp_dom_info_to_db
post_port_sfp_info_to_db(logical_port_name, int_tbl[asic_index], transceiver_dict, stop_event)
File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 293, in …

[sonic_sfp] Handle QSFP DD keys gracefully

---

sonic_platform_base/component_base.py

Added constants to component_base for each potential return code of `auto_firmware_update()` so that vendor specific component implementations may reference these to provide the correct return codes to the firmware auto update utility. 
This provides a central location from which standardized return codes may be imported, preventing the need for potential inconsistency in vendor implementations or the use of magic numbers in vendor implementations for return code. 
Non-functional change, builds successfully and can be successfully imported from at runtime.

[component] Add return code constants for FW auto update to component_base

---

.gitignore
sonic_platform_base/sonic_eeprom/eeprom_base.py
sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

1. Use visitor pattern accessing EEPROM data
2. Provide utility functions to access redis data base
Remove EEPROM cache file and use DB instead
Manual test and regression test

[eeprom_tlv_info] Optimize EEPROM data process by using visitor pattern

---

sonic_platform_base/module_base.py

There is typo "return" vs "raise" in midplane APIs.
In midplane API, default method should be raise NotImplementedError not return NotImplementedError
In case of platforms don't have the implementation for midplane API, the default value will not be set since there is no exception raised by this function.
Run the test on pmon without implementing the method and chassisd won't complain about line:
266                 # Update db with midplane information
267                 fvs = swsscommon.FieldValuePairs([(CHASSIS_MIDPLANE_INFO_IP_FIELD, midplane_ip),
268 B->                                               (CHASSIS_MIDPLANE_INFO_ACCESS_FIELD, str(midplane_access))])

Fix typo for midplane APIs.

---

sonic_platform_base/sonic_pcie/pcie_common.py

Add to check the Pcie configuration revision to get the right configuration.
Platform vendor can add their own logic to determine the Pcie
configuration revision.

Add to check pcie configuration revision to get the right configuration.

---

sonic_platform_base/sfp_base.py

Add common definitions for getting SFP error status
- Platform API definition: `get_sfp_status`
- Related constant definitions
Signed-off-by: Stephen Sun <stephens@nvidia.com>

[sonic_platform/sfp_base] Add common definition for get SFP error status

---

sonic_platform_base/sonic_pcie/pcie_common.py

Unifying the platform api for get_pcie_aer_stats with PcieBase

Unifying the platform api for get_pcie_aer_stats with PcieBase

---

sonic_platform_base/sonic_sfp/sffbase.py

Following error is seen while parsing EEPROM fields for few transceivers.
'utf-8' codec can't decode byte 0xff in position 6: invalid start byte
EEPROM fields will not be displayed  if unicode characters are not properly.
E.g. Vendor Date: 20'u-tf--8'
Check sfpshow eeprom after making the change and verify the behavior.
[SFP_UT.txt.log](https://github.com/Azure/sonic-platform-common/files/6665180/SFP_UT.txt.log)

Fix decode error when parsing EEPROM fields

---

sonic_platform_base/module_base.py

Signed-off-by: ngocdo <ngocdo@arista.com>
Add a generic function that returns a list of asics on module. Vendors will implement their own for their platform.
The function could be used for collecting fabric asic info in each module and populating into CHASSIS_STATE_DB (https://github.com/Azure/sonic-platform-daemons/pull/175). To simplify the change, all fabric cards in system should be identical in terms of number of asics in a card.

Add a template function that returns list of asics on module

---

sonic_platform_base/sonic_sfp/qsfp_dd.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Fix for xcvrd crashes with the following trace:-
Jul  7 19:18:00.910456 str-DellEmc-z9332f-032 INFO pmon#/supervisord: message repeated 3 times: [ pcied Platform PCIe Configuration file doesn't exist!]
Jul  7 19:18:00.910586 str-DellEmc-z9332f-032 INFO pmon#/supervisord: xcvrd Traceback (most recent call last):
Jul  7 19:18:00.910656 str-DellEmc-z9332f-032 INFO pmon#/supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 8, in <module>
Jul  7 19:18:00.910722 str-DellEmc-z9332f-032 INFO pmon#/supervisord: xcvrd     sys.exit(main())
Jul  7 19:18:00.910789 str-DellEmc-z9332f-032 INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1416, in main
Jul  7 19:18:00.910858 str-DellEmc-z9332f-032 INFO …

Fix Xcvrd crash due to invalid key access in type_of_media_interface, host_electrical_interface, connector_dict

---

sonic_platform_base/sonic_pcie/pcie_common.py

This reverts commit 238d76b2f27bb0a1413e08779035906b953a0ac3.
Due to build broken on sonic-platform-daemons

Revert "Unifying the platform api for get_pcie_aer_stats with PcieBase (#197)"

---

azure-pipelines.yml

What I did
fix python gcov warning "Please install dotnet core to enable automatic generation of Html report"
more info check: Azure/sonic-snmpagent#215
How I did it
install dotnet core
How to verify it

[python coverage] fix result color bar

---

sonic_y_cable/y_cable_base.py

For multiple Y-Cable vendor support once we do have a mapping from vendor/part number to the appropriate Y-Cable module to load, we need to map appropriate port to a module as well. This PR adds definition for base abstract class.
- Basically, the key idea is once we have a port identified as being of a certain vendor and it has been identified to load a certain module, it is then needed to call the correct module/API on each port each time we call the API on the port
- it is required to maintain this mapping in memory since xcvrd does not want to read/parse this y_cable_vendor_mapping.py file again and again each time we call the Y-Cable API
- Also note that the module loaded might change during xcvrd running lifetime since cable/transceiver can be changed from one vendor to another. So …

[sonic_y_cable] add abstract class YCableBase required for Y-cable API support for multiple vendors

---

sonic_platform_base/sonic_thermal_control/thermal_manager_base.py

Update ThermalManagerBase to load an interval field from thermal_policy.json if it is available and provide a getter for this interval.
This interval can be used by thermalctld to run policies at an interval specified in thermal_policy.json, rather than a fixed constant (currently 60 seconds).
Verified that thermalctld runs without exiting.
Also ran test_thermalctld.py

Load policy interval from thermal_policy.json

---

sonic_y_cable/credo/y_cable_credo.py
sonic_y_cable/y_cable_vendor_mapping.py

This PR adds support for YCable class required for platform-daemons to use the YCable API's for credo.
Basically a vendor specific implementation of abstract YCableBase class . 
detailed design discussion can be found https://github.com/Azure/SONiC/pull/757/files
Required for transitioning to vendor agnostic API's to be called by xcvrd, so that all types of cables can be called. 
Ran the changes on Arista7050cx3 switch, making changes inside the container.

[Y-Cable][Credo] Credo implementation of YCable class which inherits from YCableBase required for Y-Cable API's in sonic-platform-daemons

---

setup.py

Curreently the way python wheel includes packages is all the subdirectories inside a package need to be also included
for them to be a package. Since in the refactor for multiple vendor Y-Cable xcvrd calls these vendor specific modules by including their name which it obtains by reading the eeprom it is required to include them inside setup.py for the wheel to know it has a package. 
add the definition inside setup.py to include sonic_y_cabe.credo as a package
This is required by all calling API's for vendor agnostic Y-Cable API's to be called for credo specific cables.
Built an image and validated the presence of the pacakge.
Ran the API's on a Arista7050cx3 switch.

[Y-Cable] add the definition inside setup.py to include sonic_y_cabe.credo as a package

---

setup.py
sonic_y_cable/microsoft/README
sonic_y_cable/microsoft/y_cable_simulated.py
sonic_y_cable/y_cable_vendor_mapping.py

This PR added y-cable driver for simulated mux. This y-cable driver conforms with the requirement of https://github.com/Azure/SONiC/pull/757/files
After the abstract y-cable base class is added for multi-vendor y-cable support, we also need a y-cable driver for simulated mux used in lab testing.
1. Update the xcvrd package in pmon docker to include the changes in https://github.com/Azure/sonic-platform-daemons/pull/197
2. Update the sonic_y_cable package in pmon docker to include the changes in this PR.
3. Create `/etc/sonic/config_db.json` on DUT.
4. Restart the pmon docker.
5. Run some dualtor test scripts.
6. Check mux status on dualtor testbed.

Add y-cable driver for simulated mux

---

sonic_y_cable/broadcom/y_cable_broadcom.py

This release goes in sync with the following firmware version of Broadcom Y cable, which is consistent with release 6
{
"version_nic_active": "D203.9.D103.1",
"version_nic_inactive": "D203.9.D103.1",
"version_nic_next": "D203.9.D103.1",
"version_peer_active": "D302.8",
"version_peer_inactive": "D302.8",
"version_peer_next": "D302.8",
"version_self_active": "D302.8",
"version_self_inactive": "D302.8",
"version_self_next": "D302.8"
}
Basically a vendor specific implementation of abstract YCableBase class .
detailed design discussion can be found https://github.com/Azure/SONiC/pull/757/files
to support the Y-Cable API required to support Broadcom's Y-Cable.
put the changes in PMON, and all API's seem to run OK.

[Y-Cable][Broadcom] upgrade to support Broadcom Y-Cable API to release 1.2

---

sonic_platform_base/sonic_sfp/qsfp_dd.py

Power class most significant bit is being improperly masked off
QSFP-DD Power class is being set incorrectly 
I verified that Power class is now being set correctly

[sonic_platform_base/sonic_sfp] Fix QSFP-DD power class mask

---

setup.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Added missing cmis package to be included during python wheel build
To fix build error while taking the latest changes from sonic-platform-common in sonic-buildimage repo:-
```
2021-11-15T04:23:19.5414058Z     from .mock_platform import MockChassis, MockFan, MockPsu
2021-11-15T04:23:19.5414420Z tests/mock_platform.py:1: in <module>
2021-11-15T04:23:19.5414747Z     from sonic_platform_base import chassis_base
2021-11-15T04:23:19.5415385Z /usr/local/lib/python2.7/dist-packages/sonic_platform_base/__init__.py:9: in <module>
2021-11-15T04:23:19.5415757Z     from . import sfp_base
2021-11-15T04:23:19.5416346Z /usr/local/lib/python2.7/dist-packages/sonic_platform_base/sfp_base.py:11: in <module>
2021-11-15T04:23:19.5416768Z     from …
```

Add missing cmis package

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

remove time counting message in functions because function running time could be difficult to predict in unit tests
It was reported the unit test results are unstable in Issue #239. It is because the function running time could be difficult to predict. Therefore, this PR is raised to resolve the instability issue. 
I modified test_cmis.py accordingly to match the change I made in cmis.py

Remove time counting message in firmware related functions 

---

sonic_platform_base/sonic_xcvr/fields/xcvr_field.py
tests/sonic_xcvr/test_xcvr_field.py

Fix RegBitField decode/encode to handle cases where it is defined under multi-byte RegFields.
If defining a RegBitField in a multi-byte RegField, the specified bitpos of the RegBitField is relative to the parent RegField. However, when decoding/encoding the RegBitField, the bitpos that is used should actually be the bitpos relative to the byte that the RegBitField occupies, rather than the original specified bitpos.
Added unit test to cover this test gap. Also ran sonic-mgmt test suite on Arista platform

[sfp-refactor] Fix RegBitField decode/encode

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py

This PR aims to fix firmware related functions
1. report updated address, count and remaining bytes info in module_fw_download() 
2. remove additional 200 ms wait time in block_write_lpl() and block_write_epl() 
3. increase max wait time to 1 min in cdb1_chkstatus() if status is not 1. If status is password error (70) it will break the wait loop. 
4. add protection to failed_status_dict
This PR aims to resolve failures due to not enough wait time. It moves all the wait to CDB status check. When status = 1 , it means success and should not wait any longer. Therefore I remove 200 ms wait time in  block_write_lpl() and block_write_epl().
It also adds extra protection when status is not defined in the failed_status_dict.
Test functions are unchanged.

fix for firmware functions 

---

sonic_platform_base/sonic_xcvr/codes/public/sff8024.py
sonic_platform_base/sonic_xcvr/xcvr_api_factory.py

Add support for CMIS-compliant QSFP xcvrs (identifer 1Eh)
QSFP xcvrs which comply to CMIS have a different id and are not currently supported by the new design
Ran tests/sonic_xcvr/
Tested on Arista platform with these xcvrs

Add CMIS QSFP support

---

sonic_platform_base/sonic_xcvr/fields/xcvr_field.py

Fix RegGroupField decode to handle dependent fields which are not defined in the same RegGroupField scope
If a field inside a RegGroupField has a dep field that is defined outside of the RegGroupField then the decode() will fail.
Tested on Arista platform with SFF-8472 compliant xcvrs (8472 memory map has fields defined which run into this case)

[sfp-refactor] Fix RegGroupField decode

---

sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/fields/consts.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_ccmis.py
tests/sonic_xcvr/test_cmis.py

**Description**
Add LP mode support for CMIS devices.
**Motivation and Context**
Low Power mode can be set in CMIS devices by reading/writing in EEPROM.
**How Has This Been Tested?**
Tested in DellEMC Z9332f platform.

[SFP-Refactor] Implement CMIS Low Power mode

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_cmis.py

Changes to support firmware upgrade CLI for QSFP-DD transceivers
1. Refactored some of the APIs so as to show firmware download/upgrade progress
2. Fixed few crashes
1. Ran unit test
2. Firmware upgrade done successfully on Inphi, Molex and Centera QSFP-DD modules

Firmware upgrade CLI support for QSFP-DD transceivers

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/codes/public/cmis.py
sonic_platform_base/sonic_xcvr/codes/public/sff8024.py
sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Fix bugs in SFP refactor.
When comparing non-sfp refactor with SFP refactor, some fields are not properly displayed.
CMIS pre-emphasis settings is broken in DellEMC Z9332f due to SFP refactor.
Tested in DellEMC Z9332f platform.
[sfp_UT.txt](https://github.com/Azure/sonic-platform-common/files/7625294/sfp_UT.txt)
[z9332f_preemp.txt](https://github.com/Azure/sonic-platform-common/files/7639646/z9332f_preemp.txt)

SFP-Refactor: bug fixes

---

sonic_platform_base/sonic_sfp/sff8436.py

The TX power values for QSFP+ sff8436 are shown the same as RX.
````
show int transceiver  eeprom  -d Ethernet68 | grep Power
Extended Identifier: Power Class 4(3.5W max), CLEI present
RX1Power: -40.0dBm
RX2Power: -40.0dBm
RX3Power: -2.7622dBm
RX4Power: -40.0dBm
TX1Power: -40.0dBm
TX2Power: -40.0dBm
TX3Power: -2.7622dBm
TX4Power: -40.0dBm
````
It's maybe typo error, the TX offsets was the same as RX offsets.
The correct values for TX and RX are shown now.
````
show interfaces transceiver eeprom --dom Ethernet68 | grep Power
Extended Identifier: Power Class 4(3.5W max), CLEI present
RX1Power: -40.0dBm
RX2Power: -40.0dBm
RX3Power: -2.9217dBm
RX4Power: -40.0dBm
TX1Power: -1.4758dBm
TX2Power: -1.2884dBm
TX3Power: 0.425dBm
TX4Power: -2.5274dBm
````

[sff8436] Fix TXPower params offset

---

sonic_platform_base/sfp_base.py
sonic_platform_base/sonic_xcvr/api/public/sff8436.py
sonic_platform_base/sonic_xcvr/api/public/sff8472.py
sonic_platform_base/sonic_xcvr/api/public/sff8636.py

sfputil show eeprom CLI crashes as "vendor_rev" key is not available in sff8436/8636.
hardware_rev key is used in place of vendor_rev and it causes the crash.
Verified in DellEMC Z9332f platform.
**Before fix:**
sfputil show eeprom -p Ethernet80
File "/usr/local/bin/sfputil", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return …

[SFP-Refactor]Fix vendor revision key issue

---

sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py

Prevent SFP logic from happening on non xcvr ports.
Recirculation ports are not physical ports and need to be ignored by xcvrd.
Not ignoring this port would lead to xcvrd calling get_sfp() on an unsupported interface and therefore crashing.
Change applied manually to a switch with its dependency https://github.com/Azure/sonic-buildimage/pull/9471
Confirmed that xcvrd no longer tries to access the `Ethernet-Rec` ports

Add recycle port to the physical ignore list

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/fields/consts.py
sonic_platform_base/sonic_xcvr/fields/xcvr_field.py
sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Fix crash in get_transceiver_info() issue #255 
Reading register fields across multiple page can result in crash. So, we split the read such that each field grouped are within the same page. This way we can skip reading page >= 01h for passive modules like DAC cable.
Verified on 400G DAC cable and AOC cable

split i2c read across pages

---

azure-pipelines.yml
sonic_platform_base/sonic_sfp/sfputilhelper.py

**Approach:**
1. Always use Config DB to get port mapping when it's available
2. When port mapping is missing in Config DB, use either `platform.json` or `port_config.ini`
On `multiasic` platforms the relevant Config DB instance will be used
* Always read port mapping from Config DB when it's available
* Fallback to `platform.json` or `port_config.ini` if needed
* manually tested
* N/A

[202012][sonic_sfp]: prefer Config DB port index mapping over platform.json/port_config.ini

---

sonic_platform_base/sonic_ssd/ssd_generic.py

Removed a `return None` in the command execution helper function `_execute_shell` in the SSD class so that command output is still parsed in the event of a non-zero exit code. 
If there is an issue found with a SSD SMART utilities may return a non-zero error code and we would still want to parse the output so we should not bail.
In addition, with the `return None` the parsing functions throw stack traces during execution. When removed, the parsing functions are able to elegantly handle missing information and the fields are left as `N/A` so there is no need for handling here. 
Tested manually on a SN2010 with a malfunctioning SSD which was initially throwing stack traces and now handles the error elegantly reporting the health as `N/A` a much more informative error than a python stack …

[ssd] Allow individual vendor parsers to handle errors

---

sonic_y_cable/credo/y_cable_credo.py

Add threading locker to protect VSC protocol
This PR also adds SKU check for firmware download in the API.
so 50G or 100G cables wont be allowed to the alternate firmware versions, meaning 50G wont be allowed to download 100G and 100G wont be allowed 50G
To solve the racing condition when multiple threads access the same port at the same time
Tested on Arista 7050

[Y-Cable][Credo] add theading locker to support thread-safe calling, add SKU check for download_firmware API. 

---

sonic_y_cable/credo/y_cable_credo.py

Currently is_link_active API was broken because it was not using the target param in the routine to give back the correct link_status of ecah side. With this change it gives the correct result. 
Required for MUX_CABLE_INFO table in streaming telemetry if the cable is disconnected or the link is down. 
```
redis-cli -n 6 hgetall "MUX_CABLE_INFO|Ethernet16"
"
9) "link_status_self"
10) "down"
11) "link_status_peer"
12) "up"
13) "link_status_nic"
14) "up"
```
Tested on actual Arista7050cx3 testbed.

[ycable][credo] Fix the is_link_active API for Credo Ycable

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Signed-off-by: Kebo Liu <kebol@nvidia.com>
enhance ssd_generic to support parsing NVME SSD info from smartctl output
Add test case for new added nvme parsing logic
in the output of smartctl, the related keys for NVME SSD are different: 
- model info key is "Model Number"
- "Percentage Used" indicates the wear-out level
- "Temperature"  provides the thermal info
The new change will look for the above keys when the device is nvme SSD
below is an example of smartctl output on an NVME SSD
```
root@sonic:/home/admin# smartctl -a /dev/nvme0n1
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.10.0-8-2-amd64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, [www.smartmontools.org](https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.smartmontools.org%2F&data=04%7C01% …
```

[SSD Generic] Add support for parsing nvme ssd model, health and temperature

---

sonic_platform_base/sonic_sfp/sfputilhelper.py

Refactored sfputilhelper API read_porttab_mappings. This API has duplicate logic as done inside get_port_config.
The get_port_config has logic to first look into config_db, fallback to hwsku/platform.json, fallback to port_config.ini. Additionally added another fallback to look into the porttabfile to allow custom porttabfile to be used.
Ran some basic platform tests. Existing UT should also cover these changes
This is to address review comment in https://github.com/Azure/sonic-platform-common/pull/258#discussion_r786128567

[sfputil]Refactoring read_porttab_mappings

---

sonic_platform_base/sonic_xcvr/api/xcvr_api.py

Signed-off-by: Oleksandr Ivantsiv <oivantsiv@nvidia.com>
Add *get_module_fw_info* method to *XcvrApi* abstract class to prevent an error on execution of sfputil show fwversion command.
An exception was raised when the command was executed with xcvr specification that doesn't support operation:
```
sfputil show fwversion Ethernet0
File "/usr/local/bin/sfputil", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```

[xcvr] Add get_module_fw_info method to XcvrApi class.

---

sonic_y_cable/credo/y_cable_credo.py

Due to PR https://github.com/Azure/sonic-platform-common/pull/222
the download_firmware_status variable of download_firmware API was not cleaned up, due to which higher layer
could sometimes see wrong values of firmware version.
This PR addresses this issue. 
After calling a firmware download and not changing this variable
```
admin@sonic:~$ show mux firmware version Ethernet0
{
"version_nic_active": "N/A",
"version_nic_inactive": "N/A",
"version_nic_next": "N/A",
"version_peer_active": "N/A",
"version_peer_inactive": "N/A",
"version_peer_next": "N/A",
"version_self_active": "N/A",
"version_self_inactive": "N/A",
"version_self_next": "N/A"
}
```
after the change
```
admin@sonic:~$ show mux firmware version Ethernet0
<versionX>
{ …
```

[Credo][Ycable] Fix Credo firmware download API download_firmware flag

---

sonic_y_cable/broadcom/y_cable_broadcom.py

This release goes in sync with the following firmware version of Broadcom Y cable, which is consistent with release 8
version : { "nic": "D103.2_D208.3", "tor_a": "D308.3", "tor_b": "D308.3" }
Basically a vendor specific implementation of abstract YCableBase class .
detailed design discussion can be found https://github.com/Azure/SONiC/pull/757/files
to support the Y-Cable API required to support Broadcom's Y-Cable.
put the changes in PMON, and all API's seem to run OK.

[y_cable][Broadcom] update the BRCM y_cable driver to release 2.0

---

sonic_y_cable/credo/y_cable_credo.py

Cable could be powered off during which the i2c to the NIC MCU would not be able to respond with which side is active. 
For such cases the log needs to be improved.
In case the cable is powered correctly but still the cable is not able to get the actve side, that would mean a faulty cable.
Added/improved the appropriate logs

[Credo][Ycable] improve logging for Server Powered off/Faulty cables

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

The code that decodes the content of the ONIE syseeprom includes a flag to
enable/disable displaying the content of the vendor extension TLV. This flag is
currently set to 'disable'. Hence the 'show platform syseeprom' command shows
the presence and size of the vendor extension TLV but does not show its
content. This commit sets the flag to 'enable' so that the vendor extension TLV
content is displayed.
The 'show platform syseeprom' command shows that the Vendor Extension TLV is present but does not show its content.
Here's what that looks like on an example platform.
```
admin@sonic:~$ show platform syseeprom
TlvInfo Header:
Id String:    TlvInfo
Version:      1
Total Length: 177
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21  11 7215 …
```

[syseeprom] Enable display of vendor extension TLV content

---

azure-pipelines.yml
sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
tests/sonic_xcvr/test_cmis.py

1. Ensure the CMIS module transition fully under SW control while transitioning from LowPwr to HighPower
2. Since now only python3 is supported, use python generator expression for few fields in CmisMmap
3. Remove python2 tests from azure pipeline
In Arista switch, 400G ZR module did not transition from LowPwr -> HighPwr. This is because LowPwrAllowRequestHW =1 by default, meaning the module LowPwr state could still be controlled by LowPwrRequestHW signal
1. python3 -m pytest 
2. Verified 400G ZR module transition from LowPwr -> HighPwr
3. Transceiver info is displayed correctly

[CMIS]Fix low-power to high power mode transition

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

The command is not showing the correct value for ssd health.
```
admin@sonic:~$ show platform ssdhealth
Device Model : M.2 (S42) 3IE4
Health       : N/A
Temperature  : 25C
```
SSD health percentage not displayed on Nokia-7215 platform.
"show platform ssdhealth" cli command
Output after fix:
```
admin@sonic:~$ show platform ssdhealth 
Device Model : M.2 (S42) 3IE4
Health       : 100%
Temperature  : 25C
```

[sonic_ssd] Nokia-7215: "show platform ssdhealth" not showing health percent

---

sonic_y_cable/credo/y_cable_credo.py
sonic_y_cable/y_cable_base.py

In this PR, there is a support for adding a mux_toggle_status variable inside the base class for mux_cable.
Using this variable the Derived classes for mux_cable can check this and return in case of a mux_toggle_status is in progress.
From the higher layer this allows ycabled to synchronize the calls and not let mux_cable toggle to go in conjunction with some of the Telemetry calls.
To get the toggle time to a minimum/ not allow i2c to transactions on the cable to collide with each other
Ran the changes on 7050cx3 arista testbed

[Credo][Ycable] changes for synchronizing executing Telemetry API's when mux toggle is inprogress

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

The `heath` metric in `ssd_generic` for innodisk SSDs is too lazy. Fix to match the entire health number rather than just the first digit. 
Manual testing on Mellanox MSN2100

[ssd_generic] Fix innodisk health regex

---

sonic_platform_base/sonic_sfp/bcmshell.py
sonic_platform_base/sonic_sfp/sfputilhelper.py
tests/0/port_config.ini
tests/1/port_config.ini
tests/platform_json/hwsku.json
tests/platform_json/platform.json
tests/sfputilhelper_test.py

read_porttab_mappings() is not able to get the multiasic  port config.   Modified function read_porttab_mapings() to pass the asic_name to allow the get_port_config() to get the port info for each asic.  Also use the extend() and update() method to update the logical, logical_to_physical, phyiscal_to_logical lists.   Also add the unit test case test_read_all_porttab_mappings() .
This change is required to handle the mutliasic platform. Fixes https://github.com/Azure/sonic-buildimage/issues/10569
The following output should be displayed without any error when using CLI command: sudo sfpulti show presence
```
admin@sonic:~$ sudo sfputil show presence
Port        Presence
----------  -----------
Ethernet0   Not present
Ethernet1   Not present
Ethernet2   Present
Ethernet3   Present
Ethernet4 …
```

[multiasic][sfputil]Fix the sftpuitlhelper on mutilasic platform issue

---

sonic_platform_base/chassis_base.py
sonic_platform_base/sfp_base.py

The API returns the masks of all types of port or cage that can be supported on the port
All the types are defined in sfp_base.SfpBase
Currently, the API is used to check whether a port is an `RJ45` port so we suggest supporting it at least for `RJ45` ports
Signed-off-by: Stephen Sun <stephens@nvidia.com>

Support get_port_or_cage_type

---

sonic_platform_base/sonic_xcvr/api/xcvr_api.py

When insert trasnceiver which is not QSFP-DD, "sfputil show error-status -hw" would fail
error:
```
File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 211, in get_error_description
return api.get_error_description() if api is not None else None
AttributeError: 'Sff8636Api' object has no attribute 'get_error_description'
```
Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>
```
admin@as9726-32d-1:~$ sudo sfputil show error-status -hw
Port         Error Status
-----------  --------------------
Ethernet0    OK (Not implemented)
Ethernet8    OK (Not implemented)
Ethernet16   OK (Not implemented)
Ethernet24   OK (Not implemented)
Ethernet32   OK (Not implemented)
Ethernet40   OK (Not implemented)
Ethernet48   OK (Not implemented) …
```

Fix AttributeError for "sfputil show error-status -hw"

---

sonic_platform_base/psu_base.py

Add PSU input voltage and input current.
Description
psud would collect input voltage and input current of the PSU.
Motivation and Context
more information about the PSU.
How Has This Been Tested?
unitests, manual tests.
Additional Information (Optional)

add psu input voltage and current

---

sonic_y_cable/credo/y_cable_credo.py

Signed-off-by: xinyu <xinyu0123@gmail.com>
The original get_uart_stat() will only report the last record of the uart statistic due to all record shared the same object instance.

[Credo][Ycable] fix incorrect uart statistics

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmisVDM.py
tests/sonic_xcvr/test_cmisVDM.py

Signed-off-by: Kebo Liu <kebol@nvidia.com>
To protect the code from crashing by catching the exception
This is to fix the issue https://github.com/sonic-net/sonic-buildimage/issues/11525
run sonic-mgmt  sfp reset test case: platform_tests/sfp/test_sfputil.py::test_check_sfputil_reset  to make sure xcvrd will not crash

[CMIS] Catch Exception to avoid CMIS code crash

---

tests/pcie_common_test.py

Add unit testcases for pcie_common.py
Code coverage improved to 86%.
To improve code coverage for pcie_common.py
```
abalac@f38b3ed3cc02:/sonic/src/sonic-platform-common/tests$ pytest-3 pcie_common_test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-platform-common, inifile: pytest.ini
plugins: pyfakefs-4.5.6, cov-2.6.0
collected 4 items
pcie_common_test.py::TestPcieCommon::test_get_pcie_devices PASSED                                                                                                              [ …
```

[sonic-pcie] Add unit testcases for pcie_common.py

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Signed-off-by: Kebo Liu <kebol@nvidia.com>
When the CMIS cable EEPROM is not ready,  `get_transceiver_info` should return None to notify XCVRD that cable EEPROM is not ready instead of returning a dictionary including 'None' values.
If any field is 'None', we consider the CMIS cable EEPROM is not fully ready yet.  
`get_transceiver_info`  should return a dictionary including the correct field and values to XCVRD, if EEPROM is not ready should not return a dictionary with incorrect values. The 'None' return value can trigger XCVRD to start the retry EEPROM reading flow.
This is also to fix issue https://github.com/sonic-net/sonic-buildimage/issues/11525
keep run sfputil reset test case and see no further crash.

[CMIS] 'get_transceiver_info' should return 'None' when CMIS cable EEPROM is not ready 

---

sonic_platform_base/component_base.py

issue : https://github.com/sonic-net/sonic-mgmt/issues/4564
When the image file path doesn't exit, returns False instead of throwing error.

Update the return of update_firmware for the image not exist case

---

azure-pipelines.yml

sonic-swss-common lib will add dependency to libyang soon, so need install libyang lib to prevent build and UT break.
Modify azure pipeline to install libyang in azure pipeline steps.
Pass all UT.
Modify azure pipeline to install libyang in azure pipeline steps.

Install libyang to azure pipeline

---

sonic_y_cable/y_cable_base.py

This PR adds the following API's useful for muxcable MCU's debug, these are added as base class for muxcable API's and implemented by vendor
```
def queue_info(self):
This API should dump all the meaningful data from the eeprom which can
help vendor debug the queue info currently relevant to the MCU
using this API the vendor could check how many txns are currently in the queue etc
for debugging purposes
def reset_cause(self):
This API should return the reset cause for the NIC MCU.
This should help ascertain whether a reset was caused by soft reboot or
cable poweroff
def operation_time(self):
This API should return the time since the cable is powered on from NIC MCU side
This should be helpful in debugging purposes as to if/when the …
```

[ycable] add definitions of some new API's for Y-Cable infrastructure

---

sonic_y_cable/credo/y_cable_credo.py

- fix the switch_count_tor_a() will always clear the counter after read issue.
- use YCable.EEPROM_ERROR due to the definition was moved.
- check and activate firmware by the inactive firmware version individually.
- add more error exception for activate_firmware()

[Credo][Ycable] enhancement and error exception for some APIs

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py
tests/sonic_xcvr/test_cmis.py

[Cloudlight] QSFP-DD FW upgrade doesn't work (#257)
* Fix : cdb1_chkstatus crash when i2c NACK or timeout.
* Feat : Waiting a delay in "run_fw_image" to ensure it is really executed.
* Feat : Returning a error package when get none in "get_module_fw_info".
* Fix : Using real length to replace fixed number in "block_write_epl" function.
* I2C of transceiver might NACK or stretching when FW upgrade, assuming "None" means "CdbIsBusy" until timeout.
* "run_fw_image" will be executed after a delay which according to run command, waiting the delay in "run_fw_image" to avoid sending another command before it really be executed.
* CDB commands will maybe cause few seconds NACK or stretching on i2c bus depend on implementation of module, handling this situation for compatible with different …

Cdb fw upgrade

---

sonic_y_cable/credo/y_cable_credo.py

this PR removes some of the toggle synchronization logic for SONiC telemetry, since SONiC telemetry table MUX_CABLE_INFO is anyways disabled/enabled using CLI
```config muxcable telemetry enable/disable```, it is redundant to have this logic embedded in ycabled and port_instance helper objects, which could be unneccessary
Deploying changes on Arista testbed

[credo][ycable] remove mux-toggle inprogress flags for some API's

---

sonic_platform_base/sonic_pcie/pcie_common.py
tests/pcie_common_test.py

Signed-off-by: maipbui <maibui@microsoft.com>
`subprocess()` - use `shell=False`, use list of strings Ref: [https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation](https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation)
`subprocess()` - when using with `shell=True` is dangerous. Using subprocess function without a static string can lead to command injection.
Pass UT `tests/pcie_common_test.py`

Remove shell=True

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/codes/public/cmis.py
sonic_platform_base/sonic_xcvr/fields/consts.py
sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Read CMIS data path state duration
Read page 0x1, reg 144 to get the data path max init/deinit duration. 
The data path max init duration will replace the CMIS_DEF_EXPIRED in xcvrd.
build passes
n/a

Read CMIS data path state duration

---

sonic_platform_base/sonic_sfp/sff8436.py

Support decoding power class 5~7 for sff8436. The issue does not exist on master.
`show interfaces transceiver eeprom -d` displays Unknown power class for cables who support power class 5~7. The PR is aimed to fix it.
Manual test.

[202012] Fix issue: sff8436 does not support decoding power class 5~7

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Catch both `TypeError` and `AttributeError` in `CmisApi::get_application_advertisement` because an AttributeError will be thrown when updating a dict with `None`.
Manually test
Added unit test

 CmisApi::get_application_advertisement catch AttributeError as well 

---

sonic_platform_base/sonic_xcvr/api/public/sff8436.py
sonic_platform_base/sonic_xcvr/api/public/sff8636.py
tests/sonic_xcvr/test_sff8436.py
tests/sonic_xcvr/test_sff8636.py

Fix issue: copper cable should not display DOM information
For sff8636 and sff8436 cables, there is no DOM information. Need not read DOM data if cable is copper.
Manual test

Fix issue: copper cable should not display DOM information

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py

For cmis cable, tx power and rx power is not rounding as other eeprom fields
Fix issue: rounding float value for txpower and rxpower
Manual test

Fix issue: rounding float value for txpower and rxpower

---

sonic_platform_base/sonic_ssd/ssd_generic.py

Deduce SSD vendor name from part number for Virtum
Currently, ssd_generic.py deduce vendor name by `smartctl` command. For example,
```
Device Model:     StorFly VSFDM8XC240G-V11-T
```
"StorFly" is the vendor name. However, for some SSD vendor, `smartctl` cannot get vendor name. For example:
```
Device Model:     VSFDM8XC240G-V11-T
```
In such case, vendor name shall be deduced from part number.

[SSD] deduce vendor name from part number for Virtium

---

sonic_platform_base/psu_base.py
tests/psu_base_test.py

Two new platform APIs for PSU
- get_psu_power_warning_suppress_threshold
- get_psu_power_critical_threshold
Signed-off-by: Stephen Sun <stephens@nvidia.com>

Add warning/critical thresholds for PSU power

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Add media assignment options to Application Advertisement
Add media assignment options to Application Advertisement
Manual test

[202205] [Backport] Add media assignment options to Application Advertisement

---

azure-pipelines.yml

Upgrade to the build to bullseye
Fix the branch reference issue

[Ci] Upgrade to bullseye and fix the branch reference issue

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

The VEMDOR_EXT field parse the data and format each in byte in hex with space as separator.  But the logic leaves a space at the end of the value.  This PR removes the trailing space in output of the VENDOR_EXT field in the eepromTlvInfo decode 
This change is needed by 202205 branch
The trailing space at end of the VENDOR_EXT field cause the test of function get_system_eeprom_info() failed.  The trailing space of the data filed is invisible char in the show platform syseeprom output while the get_system_eeprom_info() return a dictionary with trailing space in the end.  This results in a mis-matched in the test case.    
```
admin@sonic:~$ show platform syseeprom 
TlvInfo Header:
Id String:    TlvInfo
Version:      1
Total Length: 177
TLV Name          Code      Len  Value …
```

[syseeprom] Remove the trailing space in the value of VENDOR_EXT field in the eepromTlvInfo decoder

---

sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
tests/sonic_xcvr/test_ccmis.py

Add get_transceiver_status and get_transceiver_pm to API interface
1. Add get_transceiver_status to API interface
2. Add get_transceiver_pm API interface in xcvr_api.py
3. Ignore if "Rx Signal Power" related fields not existing.
4. Fix a typo in get_pm_all()
Plz refer to parent PR for UT.
> **Note**
> This PR serves as dependency for https://github.com/sonic-net/sonic-platform-daemons/pull/304

Add get_transceiver_status and get_transceiver_pm to API interface

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

This PR will track the resolution for failure seen on Mellanox devices with SONiC management test failure for test_pmon_syseepromd_kill_and_start_status test case. The testcase is failing with the below error:
```
========================================================================= ERRORS =========================================================================
______________________________________________ ERROR at setup of test_pmon_syseepromd_term_and_start_status ______________________________________________
duthosts = [<MultiAsicSonicHost str2-sn3800-02>], rand_one_dut_hostname = 'str2-sn3800-02'
@pytest.fixture(scope='module')
def data_before_restart(duthosts, rand_one_dut_hostname):
duthost = duthosts[rand_one_dut_hostname]
>       data = collect_data(duthost)
duthost    = …
```

Removing null characters while decoding from syseeprom

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py

Add error handling to get_aux_mon_type API
get_aux_mon_type reads field consts.AUX_MON_TYPE in eeprom on page 1 address 145
If memory model is flat, there is no page 1 in eeprom, only 0_lower and 0_upper
Here get_aux_mon_type doesn't check whether memory model is not flat, this causes errors in running xcvrd
Tested on testbed, assured that logs of failed eeprom reading disappeared

Fix get_aux_mon_type xcvr API

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Signed-off-by: Mihir Patel <patelmi@microsoft.com>
It seems that the get_tx_bias API returns dictionary instead of list for 400GAUI-8C2M which is causing platform_tests/api/test_sfp.py::test_get_tx_bias test to fail.
Fixes sonic-net/sonic-buildimage#13380
The return for this function has now been changed to list.
Summary
1. Ensure get_tx_bias returns list - Cisco [Passed]
2. Ensure get_tx_bias returns list - Arista [Passed]
3. Ensure test_get_tx_bias passes [Passed]
For detailed unit-test, please refer to [Unit-test_get_tx_bias .txt](https://github.com/sonic-net/sonic-platform-common/files/10494570/Unit-test_get_tx_bias.txt)

Change get_tx_bias return type to list

---

sonic_platform_base/fan_drawer_base.py
sonic_platform_base/psu_base.py

Import `sys` in modules where it was missing and attempted to be referenced. Found it missing in psu_base.py and fan_drawer_base.py.
`sys.stderr.write` is used in default API definitions within psu_base.py and fan_drawer_base.py. When an exception is caught within these APIs, they will throw `NameError: name 'sys' is not defined` when trying to use the `sys` module without first importing it. Issue was originally found for PSUs, but also exists within fan_drawer_base.
Test code demonstrating the issue and the fix after importing `sys`
```
>>> def test(index):
...     l = []
...     try:
...         return l[index]
...     except IndexError:
...         sys.stderr.write('Index out of range\n')
...     return None
...
>>> test(1)
File "<stdin>", line 4, in …
```

Add missing sys imports to psu_base and fan_drawer_base

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/codes/public/sff8024.py

Update host electrical interface for 2x100G AOC
It seems that the host electrical interface for 2x100G AOC was not part of HOST_ELECTRICAL_INTERFACE. The corresponding change has now been made.
Also, updating value for "specification_compliance" had a code duplication. I have now removed the corresponding duplicate entry for this.
Verified that 2x100G AOC is detected and CMIS init code is triggered

Update host electrical interface for 2x100G AOC

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

For virtium SSD, sometimes there is no NAND_Endurance and Average_Erase_Count field in SSD smart attributes. We should use Remaining_Life_Left in such case.
To support SSD health on more virtium SSD
Manual test
Unit test

[ssd_generic] Get health status from Remaining_Life_Left field for virtium SSD

---

azure-pipelines.yml

PR pipeline failed for apt-get purge return code change.
We need to ignore return code when purge packages.
Download necessary packages to accelerate download step.

Fix pipeline apt-get purge error.

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Description:
The command is not showing the correct value for ssd health and temperature.
admin@sonic:~$ show platform ssdhealth
Device Model : M.2 (S42) 3IE4
Health       : N/A
Temperature  : N/A
Motivation and Context:
SSD health percentage and temperature not displayed on Nokia-7215 platform.
How Has This Been Tested?
"show platform ssdhealth" cli command on Nokia-7215 and Unittests
Output after fix:
admin@sonic:~$ show platform ssdhealth
Device Model : M.2 (S42) 3IE4
Health       : 100%
Temperature  : 25C

[sonic_ssd] Nokia-7215: Fix "show platform ssdhealth"

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

The changes with this PR needs to be merged along with sonic-net/sonic-platform-daemons#342
The API get_host_lane_assignment_option doesn't return the host_lane_assignment_options using the application id and always returns value from Application Descriptor 1 (AppSel = 1)
The API get_host_lane_assignment_option will now take the AppSel id as the input and would return the host_lane_assignment_option from the relevant Application Descriptor
Testcase summary
Please refer to the test details attached to sonic-net/sonic-platform-daemons#342

Modify get_host_lane_assignment_option to return value based on application id

---

sonic_platform_base/sonic_xcvr/api/public/sff8436.py
sonic_platform_base/sonic_xcvr/api/public/sff8636.py
tests/sonic_xcvr/test_sff8436.py
tests/sonic_xcvr/test_sff8636.py

Add set/get_lpmode APIs for sff8436 and sff8636 optics
Add set/get_lpmode APIs implementation in sff8436.py and sff8636.py
According to 8436 and 8636 spec, lpmode can be manipulated via the combination of the Power_over-ride and Power_set software control bits (Address A0h, byte 93 bits 0,1),  as sfp refactor came in, such logic needs to be in sonic-platform-common, thus add set/get_lpmode implementation following the spec.  
This is common routine based on standard spec. Vendor/platform can decide to whether use it or combine it with platform specific actions. 
CMIS/C-CMIS already has the support, thus no need to add.
1. Verified set/get APIs on 100G optics. checked eeprom dump/tx_power/rx_power after setting lpmode. (when optics is in lpmode, oper_status is down, and there's no …

Add set/get_lpmode APIs for sff8436 and sff8636 optics

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py
tests/sonic_xcvr/test_sff8436.py
tests/sonic_xcvr/test_sff8472.py
tests/sonic_xcvr/test_sff8636.py

Backport https://github.com/sonic-net/sonic-platform-common/pull/355 to 202211
When a function may return None, caller should always check the return value before using it. This PR is to fix such issues in sonic-xcvr.
When a function may return None, caller should always check the return value before using it. This PR is to fix such issues in sonic-xcvr.
Created unit test cases to avoid such thing happening

[Backport] [202211] Fix issue: should always check return value of a function if the function may return None

---

sonic_platform_base/sonic_ssd/ssd_emmc.py
tests/ssd_emmc_test.py

Add a new class EmmcUtil that implements the SsdBase API. This new class can be used by platforms using eMMC to implement SSDUtil.
The class EmmcUtil is copied from the Arista platform code.
The default ssd_generic.SsdUtil class doesn't support eMMC. This PR allows using EmmcUtil to support the ssdutil utility.
New test ssd_emmc_test.py

[sonic_ssd] add ssd_emmc.py with EmmcUtil

---

sonic_platform_base/sonic_xcvr/codes/public/sff8024.py

Update host electrical interface for 2x400G breakout cable
It seems that the host electrical interface for 2x400G breakout cable was not part of HOST_ELECTRICAL_INTERFACE. The corresponding change has now been made.
Snippet of the host electrical interface code from SFF-8024 spec, Rev 4.10 (Table 4-5)
Verified that 2x100G AOC is detected and CMIS init code is triggered

Update host electrical interface for 2x400G breakout cable

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py
tests/sonic_xcvr/test_sff8436.py
tests/sonic_xcvr/test_sff8472.py
tests/sonic_xcvr/test_sff8636.py

Backport https://github.com/sonic-net/sonic-platform-common/pull/350 to 202205
When a function may return None, caller should always check the return value before using it. This PR is to fix such issues in sonic-xcvr.
When a function may return None, caller should always check the return value before using it. This PR is to fix such issues in sonic-xcvr.
Created unit test cases to avoid such thing happening

[Backport] [202205] Fix issue: should always check return value of a function if the function may return None

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/codes/public/sff8024.py

Adding host electrical interface ID for 800G and 100G
- Added host electrical interface ID for 800G and 100G.
- Also, allowing to populate application dict  if module_media_interface_id is undefined (value as 0) for an application. This is done to ensure applications after the application with module_media_interface_id as unknown can be evaluated by xcvrd to find the desired application.
Verified with a breakout optic to ensure that xcvrd finds the appropriate application

Adding host electrical interface ID for 800G and 100G

---

sonic_platform_base/sonic_eeprom/eeprom_base.py
sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
tests/eeprom_base_test.py

Replace exit() by sys.exit()
sys.exit is better than exit, considered good to use in production code.
Ref:
https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python
https://stackoverflow.com/questions/19747371/python-exit-commands-why-so-many-and-when-should-each-be-used

replace exit() with sys.exit()

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Fix a crash issue in cmis.py
Crash stack:
```
May  8 03:08:31.091994 sonic ERR pmon#xcvrd: Exception occured at DomInfoUpdateTask thread due to TypeError("'<' not supported between instances of 'NoneType' and 'int'")
May  8 03:08:31.095191 sonic ERR pmon#xcvrd: Traceback (most recent call last):
May  8 03:08:31.095191 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1735, in run
May  8 03:08:31.095218 sonic ERR pmon#xcvrd:     self.task_worker()
May  8 03:08:31.095218 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1720, in task_worker
May  8 03:08:31.095252 sonic ERR pmon#xcvrd:     post_port_dom_info_to_db(logical_port_name, self.port_mapping, self.xcvr_table_helper.get_dom_tbl(asic_index), …
```

Fix issue '<' not supported between instances of 'NoneType' and 'int'

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Existing cmis api renders media_lane_count and media_lane_assignment_options from the first application code.
These api's are updated to support the modules with multiple app code, 
Not able to retrieve media information from the selected application to control the media
Create data path using any app code other than the first one advertised in the module and control the media lane 
(i.e) create breakout subports and control individual channel

Render Media lane and Media assignment options info from Application Code

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_cmis.py

It seems that currently, "sfputil show fwversion" doesn't display the inactive FW version from EEPROM after CDB FW is downloaded on a module with single bank.
We need to display the inactive FW version from EEPROM in such case to ensure that user doesn't re-download the target FW if it is already residing on the module but is not activated.
Also, the TRANSCEIVER_INFO table currently doesn't display the build version for active/inactive FWs.
"sfputil show fwversion" doesn't display the inactive FW version from EEPROM after CDB FW is downloaded on the module with single bank. Hence, this PR will track the fix for it.
Also, the TRANSCEIVER_INFO table currently doesn't display the build version for active/inactive FWs. We are now displaying the FW version using CDB command and not through …

Retrieve FW version using CDB command for CMIS transceivers + handle single bank FW versioning

---

sonic_platform_base/sfp_base.py
sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/public/sff8436.py
sonic_platform_base/sonic_xcvr/api/public/sff8472.py
sonic_platform_base/sonic_xcvr/api/public/sff8636.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
tests/sonic_xcvr/test_cmis.py
tests/sonic_xcvr/test_sff8436.py
tests/sonic_xcvr/test_sff8472.py
tests/sonic_xcvr/test_sff8636.py

Move tx_disable/tx_disabled_channel from get_transceiver_status API (which serves DOM_SENSOR table) to get_transceiver_status API (which serves STATUS table)
Also, add get_transceiver_status API for non-CMIS optics for the following fields: rx_los tx_fault tx_disable tx_disabled_channel
> **Note**
> Separate PR in SONiC repo will take care of the table schema change. https://github.com/sonic-net/SONiC/pull/1316
According to updated [schema of STATUS table in HLD](https://github.com/sonic-net/SONiC/blob/master/doc/platform_api/CMIS_and_C-CMIS_support_for_ZR.md#214-transceiver-status-table), tx_disable/tx_disabled_channel should belong to STATUS table instead of DOM_SENSOR table.
Verified on 400G optics, tx_disable/tx_disabled_channel are in the output of new status API, and in the DB as …

Move tx_disable/tx_disabled_channel/rx_los/tx_fault  to get_transceiver_status API

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Currently, we are using "Low Raw" column to calculate SSD health, but "Value"column should be used according to vendor document.
Fix issue that SSD health display wrong value
Manual test
Unit test

Fix issue: should use 'Value' column to calculate the health percentage for Virtium SSD

---

sonic_platform_base/sonic_xcvr/api/public/c_cmis.py

What I did:
Comment out tx power validation check and program the passed value  to eeprom write function
MSFT ADO: 17893499
Why I did:
For some of our 400G ZR optics calibrated value of tx power is not in min and max range of advertised value which causes xcvrd to crash and then links do not come up . This fix is short term solution to skip the validation check.
How I verify:
After this change not seeing xcvrd crash.

Comment out tx power validation check and program the passed value 

---

sonic_platform_base/sonic_xcvr/fields/xcvr_field.py
tests/sonic_xcvr/test_xcvr_field.py

Added new field RegBitsField. This will allow read/write single or more bits in a group of fields.
This allows to write fields that are 1bit or more but < 1 Byte
Added unit test for different bit sizes.

Added new RegBitsFields

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Add new SSD vendor "Swissbit" support
Add new SSD vendor "Swissbit" support
Unit test
Manual test

Add new SSD type support

---

sonic_platform_base/sfp_base.py
sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/public/sff8436.py
sonic_platform_base/sonic_xcvr/api/public/sff8472.py
sonic_platform_base/sonic_xcvr/api/public/sff8636.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
tests/sonic_xcvr/test_cmis.py
tests/sonic_xcvr/test_sff8436.py
tests/sonic_xcvr/test_sff8472.py
tests/sonic_xcvr/test_sff8636.py

All the related PRs for status CLI:
| Repo | PR Title | 
| --- | --- | 
| sonic-platform-common | [Move tx_disable/tx_disabled_channel/rx_los/tx_fault to get_transceiver_status API (cherry-pick to 202205) #395](https://github.com/sonic-net/sonic-platform-common/pull/395) | 
| sonic-utilities | [Add transceiver status CLI to show output from TRANSCEIVER_STATUS table (cherry-pick to 202205)](https://github.com/sonic-net/sonic-utilities/pull/2950) | 
Cherry pick below PR [Move tx_disable/tx_disabled_channel/rx_los/tx_fault to get_transceiver_status API](https://github.com/sonic-net/sonic-platform-common/pull/359) to 202205 branch.
Auto-cherry-pick has conflicts.
Verified status CLI output on a testbed running 202205 sonic-buildimage with 100G/400G optics plugged in. …

Move tx_disable/tx_disabled_channel/rx_los/tx_fault  to get_transceiver_status API (cherry-pick to 202205)

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Backport commits:
07ccd27 Fix issue: should use 'Value' column to calculate the health percentage
6d2d7a3 [ssd_generic] Get health status from Remaining_Life_Left field for virtium SSD (#344)
feb5036 [SSD] deduce vendor name from part number (#322)
Currently, we are using "Low Raw" column to calculate SSD health, but "Value"column should be used according to vendor document.
Fix issue that SSD health display wrong value
Manual test
Unit test

[202205] Fix issue: should use 'Value' column to calculate the health percentage for Virtium SSD

---

sonic_platform_base/sonic_xcvr/xcvr_api_factory.py

Fix exception occurred during decode vendor name and vendor pn. This exception occurs for non CMIS modules. The vendor name and vendor pn are at different offsets. 
fixes: https://github.com/sonic-net/sonic-buildimage/issues/16838

Fix exception occurred during decode vendor name and vendor pn

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Fix SSD health percentage issue for vendor Virtium device `VSFDM8XC240G-V11-T`
The SSD health percentage is calculated using `100 * (1 - NAND_endurance / Average_Erase_Count)` or `Remaining Life Left` if either of the attributes is undefined.
On this device, `NAND endurance` is not defined, and `Remaining Life Left` is not recognized by `SmartCmd` or `smartctl`. We have to parse the health percentage using the ID of `Remaining Life Left` which is 231 according to the vendor.
Unit test and manually test on different Virtium devices (`VSFDM8XC240G-V11-T` and `StorFly VSF302XC016G-MLX1`
The output of `smartctl` for a `VSFDM8XC240G-V11-T` device
```
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.10.0-18-2-amd64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, …
```

Fix SSD health percentage issue for vendor Virtium

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Fix SSD health percentage issue for vendor Virtium device `VSFDM8XC240G-V11-T`
This is to backport #407 to 202305 branch
The SSD health percentage is calculated using `100 * (1 - NAND_endurance / Average_Erase_Count)` or `Remaining Life Left` if either of the attributes is undefined.
On this device, `NAND endurance` is not defined, and `Remaining Life Left` is not recognized by `SmartCmd` or `smartctl`. We have to parse the health percentage using the ID of `Remaining Life Left` which is 231 according to the vendor.
Unit test and manually test on different Virtium devices (`VSFDM8XC240G-V11-T` and `StorFly VSF302XC016G-MLX1`
The output of `smartctl` for a `VSFDM8XC240G-V11-T` device
```
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.10.0-18-2-amd64] (local build)
Copyright (C) 2002-20, …
```

Backport to 202305: Fix SSD health percentage issue for vendor Virtium (#407)

---

sonic_platform_base/sonic_xcvr/mem_maps/public/sff8636.py
sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
tests/sonic_xcvr/test_xcvr_api_factory.py

Fix issue: https://github.com/sonic-net/sonic-buildimage/issues/17163 
1. It should first read the revision compliance to decide which standard to use 8636 should be used if it is greater than 3
2. For 8636 "Specification compliance", the bit 7 should be ignored and be parsed in "Extended Specification Compliance"
Signed-off-by: Stephen Sun <stephens@nvidia.com>
QSFP module with id 0x0d can be parsed using either 8636 or 8434
Manual and unit test

Fix issue: QSFP module with id 0x0d can be parsed using 8636

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

This PR has definition of APIs to retrieve transceiver specific information.
The change set is part of implementation of the HLD [OA crash handling to reinitialize port through xcvrd](https://github.com/sonic-net/SONiC/pull/1432)
Please refer to https://github.com/sonic-net/sonic-platform-daemons/pull/403 for the test results.

APIs to help in finding NPU SI settings

---

sonic_platform_base/sonic_sfp/sfputilhelper.py
tests/sfputilhelper_test.py

* Fix the order of the SfpUtilHelper.logical
* Update test_read_port_mappings, test_read_all_port_mappings to check every port element to make sure the order is right
* Fix typo physical_to_logica -> physical_to_logical
Fix #415 
I've modified the test to check each port order is correct.
```
root@sonic:/home/admin# sfputil show eeprom
Ethernet0: SFP EEPROM detected
Active App Selection Host Lane 1: N/A
Active App Selection Host Lane 2: N/A
Active App Selection Host Lane 3: N/A
Active App Selection Host Lane 4: N/A
Active App Selection Host Lane 5: N/A
Active App Selection Host Lane 6: N/A
Active App Selection Host Lane 7: N/A
Active App Selection Host Lane 8: N/A
Active Firmware Version: N/A
Application Advertisement: 400G CR8 - Host Assign (0x1) - Copper cable - Media Assign (Unknown) …
```

Fix the order of the SfpUtilHelper.logical (#415)

---

sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_sfp_optoe_base.py

We currently need to implement set_optoe_write_timeout API to dynamically change the write timeout value in optoe kernel driver.
The API is planned to provide an interface to dynamically change the write_timeout value in optoe kernel driver through sysfs.
The sysfs creation is handled through https://github.com/sonic-net/sonic-linux-kernel/pull/370
```
Before changing value of write_timeout
root@sonic:/sys/bus/i2c/devices/31-0050# cat write_timeout 
25
After changing the write_timeout value through API
>>> platform_chassis.get_sfp(port_num).set_optoe_write_timeout(80)
>>> 
root@sonic:/sys/bus/i2c/devices/31-0050# cat write_timeout 
80
```
ADO - 26145674

Implementing set_optoe_write_timeout API

---

sonic_platform_base/sonic_xcvr/codes/public/sff8636.py
sonic_platform_base/sonic_xcvr/mem_maps/public/sff8636.py
sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
tests/sonic_xcvr/test_xcvr_api_factory.py

This is to backport PR #412 to 202205 branch
1. It should first read the revision compliance to decide which standard to use 8636 should be used if it is greater than 3
2. For 8636 "Specification compliance", the bit 7 should be ignored and be parsed in "Extended Specification Compliance"

[202205] Fix issue: QSFP module with id 0x0d can be parsed using 8636 (#412)

---

sonic_platform_base/sonic_xcvr/codes/public/sff8636.py
sonic_platform_base/sonic_xcvr/mem_maps/public/sff8636.py

Fix memory map parsing issue for SFF8636: `extended` can not be parsed from `10/40G Ethernet Compliance Code` due to being masked.
The field `10/40G Ethernet Compliance Code` is a bit field but is parsed as an enumeration with the assumption that only 1 bit can be set, which fails to parse a value in case more than 1 bit is set. However, the bit `extended` can co-exist with bit `40GBASE-CR4`, which means the parsing logic can fail in such cases.
In PR https://github.com/sonic-net/sonic-platform-common/pull/412 the `extended` bit was masked out but it failed to parse `extended` bit as a result.
In this PR, the combination `extended` + `40GBASE-CR4` is handled by adding the value to the enumeration.

Fix memory map parsing issue for SFF8636

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Modify the return type of `get_transceiver_info_firmware_versions` API to dictionary.
Also, remove the `active_firmware` and `inactive_firmware` fields from `get_transceiver_info` since xcvrd is now using TRANSCEIVER_FIRMWARE_INFO table to store these values.
MSFT ADO - 26788561
This PR should be merged along with https://github.com/sonic-net/sonic-platform-daemons/pull/435 and https://github.com/sonic-net/sonic-mgmt/pull/11708.
This changeset is required to store  `active_firmware` and `inactive_firmware` fields to TRANSCEVIER_FIRMWARE_INFO table in xcvrd.
Please refer to the test result details added in https://github.com/sonic-net/sonic-platform-daemons/pull/435

Change get_transceiver_info_firmware_versions return type to dict

---

sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_sfp_optoe_base.py

Cherry-pick for https://github.com/sonic-net/sonic-platform-common/pull/422
We currently need to implement set_optoe_write_timeout API to dynamically change the write timeout value in optoe kernel driver.
The API is planned to provide an interface to dynamically change the write_timeout value in optoe kernel driver through sysfs.
The sysfs creation is handled through https://github.com/sonic-net/sonic-linux-kernel/pull/370
```
Before changing value of write_timeout
root@sonic:/sys/bus/i2c/devices/31-0050# cat write_timeout 
25
After changing the write_timeout value through API
>>> platform_chassis.get_sfp(port_num).set_optoe_write_timeout(80)
>>> 
root@sonic:/sys/bus/i2c/devices/31-0050# cat write_timeout 
80
```
ADO - 26145674

[202305] Implementing set_optoe_write_timeout API

---

sonic_platform_base/sonic_ssd/ssd_generic.py

Fix the temperature parsing issue on Swissbit SSD
current implementation parsing the temperature from the end of the line(attributes 194), it assumes the output should always have "(Min/Max -1/44)"
```
193 Unknown_SSD_Attribute   0x0012   100   100   000    Old_age   Always       -       0
194 Temperature_Celsius     0x0023   100   100   000    Pre-fail  Always       -       25 (Min/Max -1/44)
195 Hardware_ECC_Recovered  0x0012   100   100   000    Old_age   Always       -       0
```
But in some cases, there could be no Min and Max value in the output, like the following, so paring from the beginning will be more robust.
```
193 Unknown_SSD_Attribute   0x0012   100   100   000    Old_age   Always       -       0
194 Temperature_Celsius     0x0023   100   100   000    Pre-fail  Always …
```

Fix the temperature parsing issue on swissbit SSD

---

sonic_platform_base/sonic_xcvr/api/innolight/fr8_800g.py
sonic_platform_base/sonic_xcvr/api/innolight/fr_800g.py
sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
tests/sonic_xcvr/test_fr_800g.py
tests/sonic_xcvr/test_xcvr_api_factory.py

DPinit timeout seen for Innolight transceiver during CMIS init + transceiver OIR causing CMIS init failure
This is caused in Cisco-Innolight because of continuous calls to CDB infra from SFPUpdate Thread while updating FW info.
In Cisco-Innolight CDB runs at foreground getting continuous NACKS to CDB calls and this is causing it to miss some CMIS calls also. 
Fix is to read FW info from eeprom page data rather than reading from CDB for Cisco_innolight only
Will update soon

DPinit timeout seen for Innolight transceiver during CMIS init + transceiver OIR causing CMIS init failure

---

sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
sonic_platform_base/sonic_xcvr/fields/consts.py
sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
tests/sonic_xcvr/test_cmisTargetFWUpgrade.py

After changing the target to remote, many sfputil commands which access transceiver EEPROM fail with the below traceback if either of the below scenario is true.
1. If the remote target had page select register set to non-zero
2. If the remote target was powered down or is removed from the device
Traceback details
```
Running command: sudo sfputil show fwversion Ethernet232
['Traceback (most recent call last):', '  File "/usr/local/bin/sfputil", line 8, in <module>', '    sys.exit(cli())', '  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__', '    return self.main(*args, **kwargs)', '  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main', '    rv = self.invoke(ctx)', '  File …
```

Handle page select and remote access check after changing SFP target

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/codes/public/sff8024.py
tests/sonic_xcvr/test_cmis.py

I updated sff8024.py to align with the SFF8024 spec by including fixes and additions. Additionally, I resolved an issue in the method responsible for retrieving the application advertisement list from the EEPROM of CMIS modules.
We encountered an issue with the application advertisement list retrieved from the get_application_advertisement() method for a specific module. Despite the EEPROM indicating support for 6 applications, the method returned only one application. This discrepancy appeared because the EEPROM's application advertisement list was missing information for the SECOND application. The implementation of get_application_advertisement() in cmis.py would terminate prematurely if information was missing for any application, causing subsequent applications to be overlooked.
To …

Aligning SONiC code with sff8024 spec

---

sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py

https://github.com/sonic-net/sonic-platform-common/blob/2606cd5fb0a58fc956577602235a9f8f84a887c6/sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py#L360-L367
here, on line 363 uses `PAGE_LENGTH`, but on line 366 uses `INIT_OFFSET`. This must be an oversight。
Although the two values are equal, they are semantically different.
None

fix: using PAGE_LENGTH instead of INIT_OFFSET

---

sonic_platform_base/sonic_storage/ssd.py
tests/test_ssd.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/19020
If the vendor utility couldn't infer the temperature, display the temperature inferred from smartctl utility
Temperature can be read from smartctl utility
```
root@sonic:/home/admin# smartctl /dev/nvme0n1 -a 
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.1.0-11-2-amd64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF INFORMATION SECTION ===
Model Number:                       Virtium VTPM24CEXI080-BM110006
SMART/Health Information (NVMe Log 0x02)
Temperature:                        39 Celsius
```
```
Before this change
root@sonic:/home/admin# show platform ssdhealth
Device Model : Virtium VTPM24CEXI080-BM110006
Health       : 100.0%
Temperature  : N/A
After this change …
```

Fix the temperature parsing in virtium nvme disks

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

There are multiple VDM observable types which are not being updated in redis-db (`TRANSCEIVER_DOM_SENSOR` table) during DOM monitoring. Hence, these fields need to be monitored periodically.
Added the missing VDM fields to be monitored as part of periodic DOM polling. Also, reading the fields based on lane id.
1. Ensured that the output of `show interface transceiver eeprom -d EthernetXX` does not change with the current changeset
2. Ensured that the advertised VDM fields by the module are pushed to the `TRANSCEIVER_DOM_SENSOR` table.
redis-db dump
```
root@sonic:/home/admin# redis-cli -n 6 hgetall "TRANSCEIVER_DOM_SENSOR|Ethernet144"
1) "temperature"
2) "56.102"
3) "voltage"
4) "3.344"
5) "tx1bias"
6) "201.896"
7) "rx1power"
8) "-11.163"
9) "tx1power"
10) "-10.32"
11) "tx2bias"
12) "0.0" …
```

Parse all VDM advertised fields during DOM monitoring

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

The logic to match the vendor-specific attribute in SSD API is not accurate. The vendor-specific attribute should start with a new line (`\n`) otherwise it can hit a false match scenario.
Unit test and manual test
Eg. if the raw value of an attribute happens to contain the ID, the next line can be matched but it is wrong.
For example the vendor-specific attribute ID is 248, but the output is like the following:
```
215 Unknown_Attribute       0x0012   100   100   000    Old_age   Always       -       4275
231 Unknown_SSD_Attribute   0x1913   100   100   025    Pre-fail  Always       -       100
235 Unknown_Attribute       0x0012   100   100   000    Old_age   Always       -       1302467136
235 Unknown_Attribute       0x0012   100   100   000    Old_age   Always       -       1302467248 …
```

[202311][SSD] Bug fix: the logic to match the vendor specific attribute is not accurate

---

sonic_platform_base/chassis_base.py
sonic_platform_base/module_base.py
tests/chassis_base_test.py
tests/module_base_test.py

Added new APIs and enhanced the required APIs in "module_base.py and chassis_base.py" to support SmartSwitch
The ChassisBase class and ModuleBase class need to support new SmartSwitch platforms. 
Some new API and some API enhancements are required to support SmartSwitch.  This has been captured in the PMON HLD document.  These changes are implementation based on those requirements.
The corresponding platform APIs were implemented.  The new CLI changes and chassisd changes invoke these APIs. UT was performed and demo was done.

Added new APIs and enhanced the required APIs in "module_base.py and

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/public/sff8436.py
sonic_platform_base/sonic_xcvr/api/public/sff8472.py
sonic_platform_base/sonic_xcvr/api/public/sff8636.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py

Currently, `is_flat_memory` could return 3 different values:
- True when the module is flat memory
- False when the module is not flat memory
- None when the EEPROM read returns None or empty bytearray
When it returns None, we should not assume that the module is NOT a flat memory. Instead, it would be safer to treat it as a flat memory.
This PR is to make `is_flat_memory` only returns two state, True or False. And if EEPROM reading returns None or empty bytearray, we should treat the module as a flat memory.
Manual test

Make is_flat_memory more robust

---

sonic_platform_base/module_base.py
tests/module_base_test.py

Added new APIs and modified reboot API in module_base.py for supporting reboot on a SmartSwitch.
These API enhancements are required to support reboot for new SmartSwitch platforms. All the requirements are captured in [reboot HLD](https://github.com/sonic-net/SONiC/pull/1699)
Modified module_base.py tests. New reboot CLI changes will invoke these APIs.

Added new Platform APIs and modified APIs for supporting reboot on a SmartSwitch

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Wait for power on/off duration advertised in EEPROM during LP mode on/off
```
Ethernet496  2072,2073,2074,2075     400G   9100    N/A   etp62a  routed      up       up  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
Ethernet500  2076,2077,2078,2079     400G   9100    N/A   etp62b  routed      up       up  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
Ethernet504  2064,2065,2066,2067     400G   9100    N/A   etp63a  routed      up       up  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
Ethernet508  2068,2069,2070,2071     400G   9100    N/A   etp63b  routed      up       up  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
root@sonic:/home/admin# sfputil lpmode on  Ethernet496
Enabling low-power mode for port Ethernet496 ... …
```

Wait for specified duration during LPmode on/off

---

sonic_platform_base/sonic_storage/ssd.py
tests/test_ssd.py

The ID of "Remaining Life Left" attribute on  'Virtium VTSM24ABXI160-BM110006' device is 231. 
However, it is not recognized by SmartCmd nor smartctl so far so we need to parse it using the ID number.
Also add a unit for this model
The Virtium prefix of the device model is shown from smartctl output, so keep it.
unit test and real hardware test
show platform ssdhealth
Device Model : Virtium VTSM24ABXI160-BM110006
Health       : 100.0%
Temperature  : 52C

Refactor parse_virtium_info to support new ssd model VTSM24ABXI160-BM110006

---

sonic_platform_base/chassis_base.py
tests/chassis_base_test.py

Add a definition for a new DPU chassis API required for querying DPU dataplane and midplane states.
A new API is required to enable querying of the DPU dataplane and midplane states. These states will be monitored by the chassisd service running on the DPU and pushed to the CHASSIS_STATE_DB upon any changes. This will allow the NPU to subscribe to DPU state changes.  
The API tests will be added in scope of chassisd changes.

[SmartSwitch] Add a new API for the DPU chassis to query dataplane and midplane states

---

sonic_platform_base/sonic_storage/ssd.py
sonic_platform_base/sonic_storage/storage_devices.py
sonic_platform_base/sonic_storage/usb.py
tests/mocked_libs/blkinfo.py
tests/mocked_libs/psutil.py
tests/test_ssd.py
tests/test_storage_devices.py
tests/test_usb.py

1. Modified storage_devices.py to support class object instantiation for devices with NVMe and eUSB storage disks.
2. Full support for NVMe devices, limited support for eUSB per [promised Future Work on the Storage Monitoring Daemon](https://github.com/sonic-net/SONiC/blob/master/doc/storagemond/storagemond-hld.md#future-work)
3. Fixed bug within parse_generic_ssd_info() function in Ssdutil class that would overwrite disk_io_reads, disk_io_writes and reserved_blocks information for NVMe disks with `N/A` after successfully parsing said values. This is due to an indentation bug and has been fixed as part of this commit.
This PR is in line with [promised future work on the Storage Monitoring Daemon](https://github.com/sonic-net/SONiC/blob/master/doc/storagemond/storagemond-hld.md#future-work) …

Enhanced NVMe disk support, added limited eUSB disk support

---

sonic_platform_base/module_base.py
tests/module_base_test.py

Address the comments added in https://github.com/sonic-net/sonic-platform-common/pull/501
- Add negative for pci_detach() and pci_reattach()
- Remove module_name from get_bus_info(), pci_reattach() and pci_detach()
- Add MODULE_TYPE_SMARTSWITCH to reboot API. This reboot_type is used for rebooting DPUs when entire smartswitch undergoes for a reboot.
- Also fix unittests accordingly.

Add negative case for pci_detach() and pci_reattach()

---

sonic_platform_base/sonic_xcvr/api/public/sff8472.py
tests/sonic_xcvr/test_sff8472.py

Implement get/set_lpmode API for SFF8472
The cli "sfputil show lpmode" depends on this implemenation for SFP+ ports on Arista platform. 
Run the cli "sfputil show lpmode" on Arista platform, and check the result is Off for SFP+ ports
SFF8472 does not support setting lp mode, so both get_lpmode() and set_lpmode() is returned false. This is consistent with the existing implementation for SFF8436 in https://github.com/sonic-net/sonic-platform-common/blob/master/sonic_platform_base/sonic_xcvr/api/public/sff8436.py#L334, for the condition of "if not self.get_lpmode_support() or not self.get_power_override_support()"

Implement get/set_lpmode API for SFF8472

---

sonic_platform_base/sonic_storage/ssd.py

This change adds some protection to the vendor specific parser function in ssd in case of any failures.
iSmart utility on Nokia-7215 is returning the following error (tested on 2 devices, 1st 202311 and 2nd 202405):
Image version: 202311
```
root@sonic-switch-1    :~# iSmart /dev/sda
OCI runtime exec failed: exec failed: unable to start container process: exec /usr/bin/iSmart: exec format error: unknown
root@sonic-switch-1    :~#
```
Image version: 202405
```
root@sonic-switch-2    :~# iSmart -d /dev/sda
OCI runtime exec failed: exec failed: unable to start container process: exec /usr/bin/iSmart: exec format error: unknown
root@sonic-switch-2    :~#
```
This error is causing stormond in 202405 images to not instantiate an SsdUtil object due to OSError:
```
> …
```

Fall back to generic info if vendor specific parser fails

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

The "get_error_description" function should return 'OK' instead of 'None' when there are no errors.
When there are no errors on the cable, get_error_description currently returns 'None'. In this case, we should return 'OK' so that the CLI (show interface transceiver error-description) provides a proper output. 
Call this API directly on different cables with different error statuses.

[CMIS]The "get_error_description" function should return 'OK' instead of None when there are no errors.

---

sonic_platform_base/sonic_storage/ssd.py

Add support for Virtium SSD which can't use SmartCMD - to use only smartctl (using generic ssd info parser).
There are Virtium SSDs which can't receive SSD info from 'SmartCMD', and must use 'smartctl' command. 
For those SSDs, after calling the generic ssd parser, the function is finished and the specific vendor parser won't be called. 
I tested it manually with a special Virtium SSD which doesn't support SmartCMD
output after the change:
root@sonic:/home/admin# show platform ssdhealth 
Disk Type    : NVME
Device Model : Virtium VTPM24CEXI080-BM110006
Health       : 100.0%
Temperature  : 52.0C
output before the change:
root@sonic:/home/admin# show platform ssdhealth 
[Error] Cannot read SMART information on device /dev/nvme0n1
Disk Type    : NVME
Device Model : Virtium …

Change Virtium SSD which doesn't support SmartCMD, to use only smartctl

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

For some transceivers, the `MaxDurationDPInit` encoded in EEPROM might be lesser than the actual time taken to reach DP init state by the transceivers. This causes the CMIS initialization to fail with the below error
```
Jan 23 19:28:12.207053 DUT1 NOTICE pmon#xcvrd[36]: CMIS: Ethernet96: 400G, lanemask=0xff, state=DP_INIT, appl 1 host_lane_count 8 retries=0
Jan 23 19:28:12.221832 DUT1 NOTICE pmon#xcvrd[36]: CMIS: Ethernet96: DpInit duration 0.5 secs
Jan 23 19:28:13.230593 DUT1 NOTICE pmon#xcvrd[36]: CMIS: Ethernet96: 400G, lanemask=0xff, state=DP_TXON, appl 1 host_lane_count 8 retries=0
Jan 23 19:28:13.234448 DUT1 NOTICE pmon#xcvrd[36]: CMIS: Ethernet96: timeout for 'DataPathInitialized' <<-- Error
Jan 23 19:28:14.250133 DUT1 NOTICE pmon#xcvrd[36]: CMIS: Ethernet96: 400G, lanemask=0xff, …
```

Override MaxDurationDPInit through software for values <= 1s

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

cmis.get_error_description is very slow for passive module:
```
>>> begin = time.time()
>>> s.get_error_description()
'ModuleLowPwr'
>>> print(time.time() - begin)
2.905252695083618
```
For a module that has flat memory, it does not need check data path state. Because of this issue, `show error-status --fetch-from-hardware` takes very long time if there are many passive modules present:
```
real    1m12.116s
user    0m5.852s
sys     0m15.491s
```
After the fix, it changes to:
```
real    0m1.051s
user    0m0.499s
sys     0m0.059s
```
Optimize cmis.get_error_description for passive module
Manual test
Unit test

[cmis] Optimize cmis.get_error_description speed for passive module

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_cmis.py
tests/sonic_xcvr/test_sfp_optoe_base.py

is_transceiver_vdm_supported API needs to be created so that xcvrd can directly skip freezing/unfreezing of VDM stats (done to read VDM and PM data from the transceiver) for transceivers which do not support VDM feature.
XCVRD will call `is_transceiver_vdm_supported` API before performing freeze of VDM stats.
Following types of modules were tested with this changeset
1. CMIS module supporting VDM - ensured is_transceiver_vdm_supported returns True
2. SFF-8472 module - ensured is_transceiver_vdm_supported returns False
MSFT ADO - 30657693

Create is_transceiver_vdm_supported API for CMIS transceivers

---

azure-pipelines.yml
sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

This is 202411 dedicated version of @Junchao-Mellanox 's PR https://github.com/sonic-net/sonic-platform-common/pull/526
For copper passive modules with flat memory cmis.get_error_description should not try to read from paged memory (CMIS spec indicates page 0x11, which is irrelevant for flat memory modules) of the EEPROM instead it will read module state.
Read data path state from the correct field on the EEPROM for copper passive modules in SW mode.
Manual test
Unit test

[202411][cmis] Fix cmis.get_error_description speed for passive module

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

For CMISwe can tell if a module is copper because the media interface will always be passive_copper_media_interface. This PR adds a check for that.
Similar to other SFF xcvr api's it would be helpful to know if a CMIS module is copper or optical. We can use this information for tunings and in other areas where appropriate.
Wrote a unit test and tested manually on device using multiple optics and DACs

Adding is_copper api to cmis

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
sonic_platform_base/sonic_xcvr/fields/consts.py
sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_cmis.py
tests/sonic_xcvr/test_sfp_optoe_base.py

This PR introduces **RX disable support** for CMIS-compliant transceivers, aligning it with TX disable functionality.
- Added the following methods in `CmisApi` and `XcvrApi`:
- `get_rx_disable()`
- `get_rx_disable_channel()`
- `rx_disable()`
- `rx_disable_channel()`
- Updated `SfpOptoeBase` to expose RX disable functionality.
- Defined `RX_DISABLE_SUPPORT_FIELD` in `consts.py`.
- Added `RX_DISABLE_FIELD` at **Byte 138** in `CmisMemMap`.
- Updated `CTRLS_ADVT_FIELD` to include `RX_DISABLE_SUPPORT_FIELD`.
- Integrated RX disable methods into `sfp_optoe_base.py`, mirroring TX disable operations.
UT and deploy on testbed, please see attached testbed results
```
sfp1 = platform_chassis.get_sfp(1)>>> platform_chassis = sonic_platform.platform.Platform().get_chassis()
>>> sfp1 = …
```

Add support for rx_disable, rx_disable_channel in CMIS_API for transceivers

---

sonic_platform_base/sonic_xcvr/api/public/sff8636.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
sonic_platform_base/sonic_xcvr/fields/consts.py
sonic_platform_base/sonic_xcvr/mem_maps/public/sff8636.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sonic_xcvr/test_sff8636.py

Add platform common API support for enabling high power class if module's power class is greater or equal to 5 (Refer to SFF-8636 spec `6.2.6 Control Functions (Page 00h, Bytes 86-99)` for byte 93 definition)
Without enabling high power class for those modules, the module won't operate properly with power output and link won't come up.
Verified the module operate with proper power output.

High power class enabling for SFF-8636 modules

---

sonic_platform_base/sonic_storage/ssd.py
tests/test_ssd.py

Use 'smartctl' Transcend SSD instead of 'scopepro'. Scopepro utility is not present in debian repository and all functionality of scopepro can also be supported using generic smartctl.
Change uses 'smartctl' and its generic implementation for reading SSD parameter for Transcend SSD.
Change also removes the references of 'scopepro'.
Update the test_ssd to also use 'smartctl' output for  Transcend SSD.
fixes https://github.com/sonic-net/sonic-buildimage/issues/22163
Tested in platform using Transcend SSD with full SONIC PTF run. Test where run with 'sonic-marvell-teralynx.bin'.
Backport of fix is needed in following sonic-platform-common branches

Use smartctl for Transcend SSD

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py

The logic in get_host_lane_assignment_option() was updated to handle missing application entries more safely.
Old behavior: Returned host_lane_assignment_options if the application index was within range based on dictionary length; otherwise returned 0. This could lead to KeyError if appl was not a valid key.
New behavior:
Checks if appl exists in appl_advt.
Logs an error and returns 0 if it's missing.
Uses .get() to safely access 'host_lane_assignment_options', defaulting to 0 if the key is missing.
This improves robustness and avoids runtime errors from unexpected or unsupported application values.
Some CMIS applications—such as XDR/1.6TB and possibly others—are currently not supported by SONiC.
If a module with such applications is plugged in, xcvrd may crash due to a KeyError raised …

Fix KeyError for unsupported CMIS applications

---

sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
tests/sonic_xcvr/test_xcvr_api_factory.py

`XcvrApiFactory.create_xcvr_api` may raise exception (e.g. the EEPROM is corrupted which has non unicode character). The exception would cause xcvrd crash. The PR is to catch the exception so that  `XcvrApiFactory.create_xcvr_api` either return a None or a valid API object
When there is invalid character in module EEPROM, it would crash xcvrd and affect other healthy modules. The PR catches the exception in `XcvrApiFactory.create_xcvr_api` to prevent it affecting other modules.
unit test
manual test

[sonic-platform-common] catch exception while creating api object

---

sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py

AppSelCode in cmis uses bits 4-7, range api in python is not inclusive.
Fix range for ACTIVE_APSEL_HOSTLANE.
Reporting op active apsel is wrong for applications larger than 8.
Reading active apsel for when apsel is larger than 8.

Correct bit range for ACTIVE_APSEL_CODE

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py

Several fields in the TRANSCEIVER_INFO table currently contain trailing spaces, requiring consumers to manually trim these values. To reduce this overhead and improve data consistency, we have updated the following fields to automatically trim trailing spaces:
1. serial
2. manufacturer
3. model
4. vendor_date
5. vendor_rev
This change ensures cleaner data handling and simplifies integration for downstream consumers.
The trailing space for the relevant fields are being removed just after reading from EEPROM. This releases the caller from the overhead of trimming the trailing space.
Fields before the change
```
9) "manufacturer"
10) "PINEWAVE        "
39) "serial"
40) "IDOBIS130546    "
43) "model"
44) "T-OH8CNT-NMT    "
69) "vendor_date"
70) "2024-08-31   "
```
Fields after the change
``` …
```

[xcvrd] Trim trailing white space in fields of TRANSCEIVER_INFO table

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Backport a change from `master` to implement `is_copper` CMIS API. 
(cherry picked from commit 45b10beaabd9bd62c06b4cccdc7a497fc7c30fa2)
Backport a change (45b10beaabd9bd62c06b4cccdc7a497fc7c30fa2) from `master` to provide the `is_copper` CMIS API. 
Required for `<media>-<rate>` media settings key. (PR: https://github.com/sonic-net/sonic-platform-daemons/pull/617)
Verified correct application of media settings in 202411 based on the installed transceiver using `<media>-<rate>` media settings key.

Adding is_copper api to cmis (#547)

---

sonic_platform_base/sonic_xcvr/codes/public/sff8024.py

We need to add XCVR_IDENTIFIER_ABBRV code for Custom Amphenol Backplane Cartridge
https://github.com/sonic-net/sonic-platform-common/blob/4af4791f602e1684ea2aa940b73a50d9c8910f86/sonic_platform_base/sonic_xcvr/codes/public/sff8024.py#L45-L76
```
>>> print("Module type is {}".format(platform_chassis.get_sfp(port_num).get_xcvr_api().get_module_type_abbreviation()))
Module type is Unknown
>>> 
```
```
>>> print("Module type is {}".format(platform_chassis.get_sfp(port_num).get_xcvr_api().get_module_type_abbreviation()))
Module type is BP
>>> 
```
MSFT ADO - 34111221

Add abbreviation identifier for Custom Amphenol backplane cartridge

---

sonic_platform_base/sonic_xcvr/api/public/sff8436.py
sonic_platform_base/sonic_xcvr/api/public/sff8636.py
tests/sonic_xcvr/test_sff8436.py
tests/sonic_xcvr/test_sff8636.py

Fix the tx bias response for sff8436 and sff8636 copper interfaces. 
Tx bias of sff8436 and sff8636 interfaces would return as 0 even for copper interfaces. As copper interfaces don't support txbias, we change the return to 'N/A' for them. It keeps the behavior consistent with other DOM values.
I looked at the output of the following commands on a sonic device:
1. `sudo sfputil show eeprom` : The output remained unchanged.
2. `show interface transce eeprom` : The output remained unchanged.
3. 
```python
from sonic_platform.platform import Platform
p = Platform()
platform_chassis = p.get_chassis()
a = platform_chassis.get_all_sfps()
apis = [i.get_xcvr_api() for i in a if i]
{i.get_transceiver_info()['serial'].strip():i.get_tx_bias() for i in apis if i} …
```

Add tx bias support check before getting tx bias of sff8436 and sff8636

---

sonic_platform_base/module_base.py
tests/module_base_test.py

On startup of pmon in dark mode on switch, there are four processes spawned to power off DPUs, if all are executed in parallel there are four sensord processes running (since service restart commands are not queued). Since we perform handle_sensor_removal on dark mode start, the solution is to have a file lock to make sure only one module has control to restart sensord each time, queueing the sensord restart requests so that we have a single process running always, irrespective of number of restarts
Check the number of sensord processes starting before fix:
```
docker exec -it pmon ps -x|grep sensord
170 ?        Ss     0:00 /usr/sbin/sensord -f daemon
171 ?        Ss     0:00 /usr/sbin/sensord -f daemon
172 ?        Ss     0:00 /usr/sbin/sensord -f daemon
173 ?        Ss     0:00 …
```

[Smartswitch] Restart sensord with lock

---

sonic_platform_base/sonic_storage/ssd.py
tests/test_ssd.py

Fix health check for SSD vendors: add a parser for ATP, and add a generic health ID for other brands.
Each vendor stores health information in different SMART attributes.
ATP stores it in attribute ID 248, we add a parser for it.
We also have SSDs use Attribute ID 231 and it is commonly used, so add it in the generic parser.
Skip obtaining vendor SSD info for ATP and Virtium NVMe SSD because they are handle by parse_generic_ssd_info and parse_vendor_ssd_info will overwrite data with N/A.
Add unit test cases for ATP SATA/NVMe SSD.
`show platform ssdhealth` shows N/A health for some qualified SSDs.
We have tested the code change on DUTs with different SSDs including all the qualified SSDs that show N/A in health and also on the ones that worked fine before.

Fix health check for SSD vendors: add a parser for ATP, and add a generic health ID for other brands

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/api/xcvr_api.py
tests/sonic_xcvr/test_cmis.py

Add `is_lpo` API to check if the module is Linear Pluggable Optics (LPO)
This API will be consumed by https://github.com/sonic-net/sonic-platform-daemons/pull/687

Add API to check if module is Linear Pluggable Optics (LPO)

---

sonic_platform_base/sonic_xcvr/codes/public/cmis.py

Add missing module fault cause codes
`MODULE_FAULT_CAUSE` misses values from cmis standard.

Update MODULE_FAULT_CAUSE with additional codes (4-6)
