sonic_sfp/sfputilbase.py

[sfputilbase.py] Fix bug where 'title' list always gets overwritten with empty list

---

sonic_sfp/sfputilbase.py

Signed-off-by: Guohan Lu <gulv@microsoft.com>

add detailed comments for get_transceiver_change_event

---

sonic_sfp/sfputilbase.py

Reverts Azure/sonic-platform-common#15
bug in _is_valid_port fix

Revert "Pep 8 compliance, code cleanup"

---

sonic_sfp/inf8628.py
sonic_sfp/sff8024.py
sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sfputilbase.py

Enable decode of QSFP-DD/OSFP transceivers, and vendor information.

Add basic QSFP-DD/OSFP support for sfputil

---

sonic_sfp/inf8628.py
sonic_sfp/sff8024.py
sonic_sfp/sff8436.py
sonic_sfp/sff8472.py
sonic_sfp/sfputilbase.py

Added short type to be used in media_settings.json for Dynamic transceiver tuning.

Added type abbrev name to be used in media_settings.json for Dynamic transceiver tuning 

---

sonic_platform_base/sonic_sfp/sfputilbase.py

[sfputilbase] fix dom_module_threshold_raw and dom_channel_threshold_raw  can't assign value，
cause SFP_MODULE_THRESHOLD_OFFSET SFP_MODULE_THRESHOLD_WIDTH not defined
Signed-off-by: wangzhui <wangzhui@asterfusion.com>

[sonic_sfp] Fix a variable about sfp module not defined issue

---

sonic_platform_base/sonic_eeprom/eeprom_base.py

What I did:
- Handling the IOError produced during interacting with the eeprom through I/O operation

[eeprom] Add try-except to catch the IOError

---

sonic_platform_base/sonic_eeprom/eeprom_base.py

Fix the UnboundLocalError: local variable 'F' referenced before assignment

[eeprom] Fix UnboundLocalError

---

setup.py

Update dependencies in setup.py to align with current needs. This allows for implicit installation of dependencies at build and run time, and prevents the need to explicitly install these packages.

[setup.py] Update dependencies

---

README.md
sonic_platform_base/sonic_eeprom/eeprom_base.py
sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
sonic_platform_base/sonic_sfp/bcmshell.py
sonic_platform_base/sonic_sfp/sff8436.py
sonic_platform_base/sonic_sfp/sff8472.py
sonic_platform_base/sonic_sfp/sffbase.py
sonic_platform_base/sonic_sfp/sfputilbase.py
sonic_platform_base/sonic_sfp/sfputilhelper.py
sonic_platform_base/thermal_base.py

LGTM tool is now active for the sonic-platform-common repo.
- Add LGTM badges to README.md
- Fix 26 LGTM alerts:
- 17 for Unused import
- 9 for Except block handles 'BaseException'

Fix some LGTM alerts; Add LGTM badges to README.md

---

sonic_y_cable/y_cable.py

In SONiC testbed, y_cable is simulated by OVS in test server. An OVS
bridge is created for each of the y_cable. The PTF interface and
test server VLAN interfaces are attached to the bridge. The VLAN
interfaces are connected to DUT ports through fanout switches.
+--------------+
|              +----- upper_if
PTF (host_if) --+  OVS bridge  |
|              +----- lower_if
+--------------+
Open flow rules are configured for the OVS bridge to simulate upstream
broadcasting and downstream dropping traffic from standby side.
To further simulate y_cable active/standby querying and switching, a
process can be started in the test server. The process needs to expose
APIs for querying and switching active/standby status. When the APIs are
called, the process checks and updates open flow …

Enhance the y_cable driver to support hook y_cable_simulator_client

---

sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py

This PR fixes eeprom_tlvinfo.py to make it compatible with both Python2 & Python3. 
The current implementation causes runtime issue as follows:
```
Dec 14 12:04:34.908841 sonic WARNING pmon#syseepromd[51]: Failed to load platform-specific eeprom from sonic_platform package due to UnicodeDecodeError('ascii', '*\x02\x00\x8c', 3, 4, 'ordinal not in range(128)')
Dec 14 12:04:34.910093 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet56 admin status to up
Dec 14 12:04:34.923442 sonic ERR pmon#syseepromd[51]: Failed to load platform-specific eeprom implementation: UnicodeDecodeError('ascii', '*\x02\x00\x8c', 3, 4, 'ordinal not in range(128)')
Dec 14 12:04:34.925628 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet60 MTU to 9100
Dec 14 12:04:34.939277 sonic NOTICE …
```

Fixed eeprom_tlvinfo.py to make it Python2/Python3 compatible

---

.github/pull_request_template.md

Add GitHub pull request template

[GitHub] Add pull request template

---

sonic_y_cable/y_cable.py

Summary:
This PR provides the necessary infrastructure to add support for getting firmware information running on the three ends of Y cable. Also we get internal and nic side temperature and voltage 
Added changes in the sonic_y_cable package
To add the necessary support for  fetching firmware info for Y cable, internal and nic temperature and voltage
Added the changes in sonic-platform-common module in the y_cable.py file
opened a python shell and ran the API's manually and test verified
the values are correct.

[sonic_y_cable] add support for retrieving firmware info for Y cable, internal and nic temperature and voltage

---

sonic_platform_base/sonic_sfp/sfputilhelper.py

[sfputilhelper] Add new option in ports cache creation, fetch ports from config DB.
This change is not needed in master since in master the whole code was rewritten as part of the DPB therefore the bug was solved there (same goes for 202012).
Signed-off-by: liora <liora@nvidia.com>
**- Dependencies**
This PR is related to https://github.com/Azure/sonic-platform-daemons/pull/155 however it can be merged solely.
**- Why I did it**
Fix community issue https://github.com/Azure/sonic-platform-daemons/issues/110
Issue description: newly created ports as part of dynamic port breakout process are not being added to XCVRD cache, hence not shown in SNMP get on entPhysicalEntry mib.
**- How I did it**
Add new option in ports cache creation, fetch ports from config DB instead of port_config.ini
**- …

[201911][sfputilhelper] Add new option in ports cache creation, fetch ports from config DB

---

sonic_platform_base/sonic_pcie/pcie_common.py

Reverts Azure/sonic-platform-common#207

Revert "Revert "Unifying the platform api for get_pcie_aer_stats with PcieBase (#197)""

---

sonic_y_cable/broadcom/y_cable_broadcom.py

This release goes in sync with the following firmware version of Broadcom Y cable, which is consistent with release 7
{
"version_nic_active": "D207.1.D103.1",
"version_nic_inactive": "D207.1.D103.1",
"version_nic_next": "D207.1.D103.1",
"version_peer_active": "D307.1",
"version_peer_inactive": "D307.1",
"version_peer_next": "D307.1",
"version_self_active": "D307.1",
"version_self_inactive": "D307.1",
"version_self_next": "D307.1"
}
Basically a vendor specific implementation of abstract YCableBase class .
detailed design discussion can be found https://github.com/Azure/SONiC/pull/757/files
to support the Y-Cable API required to support Broadcom's Y-Cable.
put the changes in PMON, and all API's seem to run OK.

[Y-Cable][Broadcom] upgrade to support Broadcom Y-Cable API to release 1.3

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py

Fix LP mode API issue
Typo in invoking LP mode API 
Tested in DellEMC Z9332f platform.
[LPmode_UT.txt](https://github.com/Azure/sonic-platform-common/files/7617073/LPmode_UT.txt)

[SFP-Refactor] Fix LP mode API issue

---

azure-pipelines.yml

Update python-wheel target path to latest in master
azure pipeline builds are failing for sonic-platform-common

[build] Update python-wheel target path to latest in master

---

azure-pipelines.yml

python dependencies path changed, blocking azp

[ci] Fix python dependencies reference path

---

azure-pipelines.yml

Uplift the code coverage from 50 to 80%

Uplift the code coverage from 50 to 80%

---

sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
tests/sonic_xcvr/test_ccmis.py

Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>
implement CMIS set_laser_freq to support 100GHz grid space

implement CMIS set_laser_freq to support 100GHz grid space

---

azure-pipelines.yml

Upgrade to bullseye.
Fix the build dependency issue, need to install the libyang first.

[Ci][202205] Upgrade to bullseye and fix the branch reference issue

---

tests/thermal_manager_test.py

Fix TODO comment. As python2 is removed from sonic, this TODO comment can be fixed.
Fix TODO comment
Unit test.

Fix TODO comment

---

sonic_platform_base/sonic_xcvr/api/public/cmis.py
sonic_platform_base/sonic_xcvr/fields/consts.py
sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
tests/sonic_xcvr/test_cmis.py

Add API to get module power up and power down duration

[CMIS] Add API to get module power up duration

---

azure-pipelines.yml

* Fix pipeline apt-get purge error.

Fix pipeline apt-get purge error. (#349)

---

sonic_platform_base/chassis_base.py
tests/chassis_base_test.py

Add new APIs to ChassisBase, to support set or get system UID led.
The implementation relevant is https://github.com/sonic-net/sonic-buildimage/pull/11592

add set get uid led api

---

sonic_platform_base/sonic_ssd/ssd_generic.py
tests/ssd_generic_test.py

Backport PR https://github.com/sonic-net/sonic-platform-common/pull/390 to 202305
Add new SSD vendor "Swissbit" support
Add new SSD vendor "Swissbit" support
Unit test
Manual test

[202305] Add new SSD type support 

---

sonic_platform_base/sonic_xcvr/api/public/sff8472.py
tests/sonic_xcvr/test_sff8472.py

Implement `is_copper` for SFF8472
Implement `is_copper` for SFF8472
unit test
manual test

Implement is_copper for SFP

---

sonic_platform_base/sonic_xcvr/xcvr_api_factory.py

Update additional PN for Innolight and Eoptolink
Check if no optoe errors or other xcvrd errors seen

Update additional PN for Innolight and Eoptolink

---

sonic_platform_base/sfp_base.py
sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
tests/sfputilhelper_test.py
tests/sonic_xcvr/test_sfp_optoe_base.py

Add set_power api support to xcvr api
sfptuil command changes PR: https://github.com/sonic-net/sonic-utilities/pull/3418

Add set_power api support to xcvr api

---

setup.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/17246

Use latest natsort package

---

azure-pipelines.yml

Update the pipeline to use Bookworm and to use sonic-slave-bookworm.

Update azure pipeline to use Bookworm

---

sonic_platform_base/sonic_xcvr/xcvr_api_factory.py

support DSFP
- Microsoft ADO **(number only)**:

support DSFP
